version: "3.2"
services:
  #Primer contenedor Extracciòn de datos
  extraer:
    build: ./datos
    container_name: extraccion
    depends_on:
      - db
    restart: on-failure
    volumes:
      - type: bind
        source: ./datos
        target: /usr/src/app

  #Segundo Contenedor Base de datos de mongoDB
  db:
    image: mongo
    container_name: BaseDeDatos
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examen123

  #Tercer contenedor interfaz de mongoDB -> DBMS
  dbManager:
    image: mongo-express
    container_name: InterfazMongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: examen123
      ME_CONFIG_MONGODB_SERVER: BaseDeDatos
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: examen123

  #Cuarto contenedor Interfaz con Flask
  flaskinterfaz:
    build: ./api
    container_name: Flask_interfaz
    depends_on:
      - db
    ports:
      - 5000:5000
    restart: on-failure
    volumes:
      - type: bind
        source: ./api
        target: /usr/src/app