# EJERCICIO 2

En el ejercicio 2 lo primero que hice fue realizar la estructura del patron decorador a partir del ejercicio 1:

## Estructura
- PaginaWeb: clase que representa un documento que se puede mostrar en un navegador web.
- Component: Interfaz comun a los manejadores concretos, los métodos en común son: buscador.
- Clase Decorator:tiene un constructor donde el atributo que tiene es  _wrapper de tipo Componet y tiene dos funciones  una es basedecorador que recibe _wrape de tipo Componet y la función buscador 
- Concrete Component: hereda la clase Decorador, define la funcionalidad que se pueden añadir,  y la función buscador tiene una condición ( si _wrapper esta en el buscador del decorar ) regresará que la pagina existe, en caso contrario regresará No existe la página.
- SitioWeb: hereda la interfaz, clase que representa una colección de páginas web que se agrupan, donde tiene un constructor __init__ con sus atributos correspondientes, se define la función buscador que retorna las paginas que tiene el sitioweb.
- Cliente (funcion main) : el cliente declara primero la pagina_1, pagina_2 y  pagina_3  donde se inicializa con la clase  PaginaWeb y ahi ingresa los datos según la estructura que espera que tenga.Luego crea un sitio_web que se inicializa con la clase SitioWeb donde se le agrego  un dominio, una categoría y las páginas que tiene (pagina_1 y pagina_2).
-- Primero declaras buscar = BuscadorConctreteDecorator(sitio_web) le pasas a la clase el sitio web 
--resultado = buscar.buscador(pagina_3) ingresaras la pagina a buscar
--print(resultado) #imprime que no existe ya que no la agregue al sitio web

Realize unas pruebas unitarias donde en la primera función buscará una página qie si existe en el sitioweb y la segunda función buscará la página que no agregue y trae si existe o no la pagina.