version: '3.2'
services:
      
  sp:
    container_name: py_sp
    build:
      context: ./sp
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: on-failure
    volumes:
      - type: bind
        source: ./sp
        target: /usr/src/app

  db:
    image: mongo
    container_name: mongo_compose
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s123
  
  debms:
    image: mongo-express
    container_name: mexpress_compose
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: examen
      ME_CONFIG_BASICAUTH_PASSWORD: ex-especial567
      ME_CONFIG_MONGODB_SERVER: mongo_compose
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: s123
  api:
    container_name: py_app
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 5000:5000
    restart: on-failure
    volumes:
      - type: bind
        source: ./web
        target: /usr/src/app

