version: "3.5"
services:
    mongodb:
    build: ./dats
        container_name: mongo_db
        image: mongo:4.4
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: Vic
            MONGO_INITDB_ROOT_PASSWORD: Parc0606

        volumes:
          - volumeMongo:/var/lib/docker/volumes/mongoVolume/_data

    mongo-express:
        container_name: dbms
        image: mongo-express
        restart: always
        ports:
            - "8082:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: Vic
            ME_CONFIG_MONGODB_ADMINPASSWORD: Parc0606
            ME_CONFIG_BASICAUTH_USERNAME: Vic
            ME_CONFIG_BASICAUTH_PASSWORD: Parc0606
volumes:
    volumeMongo: