# Práctica 1 - Parte 1

¿Qué patrón es más fácil de desarrollar (Monolítica vs. Microservicios) y por qué?
- El patrón que podría ser más fácil de aplicar sería el de microservicios ya que la manera en como se organiza el proyecto mediate módulos por separado y que entre ellas tengan una comunicación para realizar las acciones debidas puede ser más accesible al cambio y tengan mayor seguridad en cuestion de los datos que se manejen, también  tienen varias ventajas al monolitico  dado que si  llegara a fallar, toda la aplicación o el proyecto va dejar de funcionar, pero todo va depender de como sea tu aplicación dado que si es grande es mejor usar los microservicios siempre y cuando tengan las personas necesarias para podero realizar, en dado caso que sea más pequeño sería usar un monolítico. 

¿En qué consiste el patrón de arquitectura monolítica?
- Consiste en que todos los archivos que se tengan algo funcional a la aplicación , esten organizados en un mismo módulo, donde la comunicación que tienen entre ellos pasa por la memoria y es el uso común que usamos al realizar una aplicación.

¿Cuáles son las principales desventajas de una arquitectura monolítica?
- Que mientras va creciendo la aplicación va ser más díficil administrar tanto la información que vayan adquierendo, como la funcionalidad que necesiten, esto va aprovocar que van a tener que hacer copias iguales en diferentes servidores y todos dependeran de una balanceador de carga que se encarga que siempre la aplicación pueda  ejecutar las peticiones de forma eficiente y pueda dividir las peticiones entre las copias.
- otra desventaja es cuando se pida una actualización de código  se tendrá que hacer lo mismo en las copias.
- La aplicación deberá ser desarrollada en un solo lenguaje de programación.
- Los componentes que se tengan en una aplicación no se podrán usar en otras aplicaciones dado que fue realizado especificamente para uno en concreto.

¿Qué problemas presenta un monolito al que queremos agregar nueva funcionalidad?
- Va ser más dificil escalar el proyecto ya que se tendrán que hacer replicas del módulo, puesto que se tendrán que poner en otros servidores y los deberán organizar en un load balancer para poder seguir teniendo una eficiencia positiva.

¿Qué sucede si falla una aplicación monolítica?
- Si una cosa falla todo dejará de funcionar, ya que todo esta en un mismo módulo.


¿En qué consiste el patrón de arquitectura basada en microservicios?
- El patrón microservicios organiza el backend mediate componentes distribuidos  por separado, puesto que cada uno tendrá una funcionalidad diferente y que entre ellas puedan tengan una comunicación y asi puedan ejecutarse como una sola, cada servicio puede depender por si mismo o por otro, ademas que pueden tener cambios con el paso del tiempo y no vana depender de los otros servicios sin interrumpirse.

¿Qué sucede si aumenta la carga en un servicio de la arquitectura basada en microservicios?
- Se va agregando más funcionalidad a la aplicación sin que interrumpa a los demás servicios que ya tenían.


¿Qué es un ambiente basado en contenedores?
- Es donde cada función del servicio se implementa en un contenedor  propio y cada uno ellos se comunican a través de una API, cada uno de ellos podrá usar el lenguaje  que necesite, una vez que pase las pruebas correctamente ya lo podrás subir a producción inmediatamente.

Si utilizaramos una arquitectura basada en microservicios, ¿seríamos dependientes a algún lenguaje/tecnología en específico o no?, ¿y por qué?
- No, porque se pueden usar diferentes lenguajes de programación en cada servicio e incluso distintas bases de datos, esto es porque no se guian por la tecnología que estén usando si no por la imformación que entra y sale de la aplicación y así puedan ralizar su tarea.

¿De qué diferentes maneras se pueden comunicar los servicios en una arquitectura basada en microservicios?
- Se comunican mediante los protocolos HTTP, mediante una API  donde permite que los servicios se comuniquen entre si, sin importar como estén realizados.


¿Los microservicios pueden ser distribuidos? ¿Por qué?
- si porque se organizan por diferentes servicios donde cada uno tiene una funcionalidad, sin importar las  diferentes tecnologíasque tengan..


¿Cuáles son los principales desafios de una arquitectura basada en microservicios?
- Un desafio sería el mantenimiento dado a la cantidad de personas que tengan en cada módulo, si son pocos será dificil poder realizarlo, ya que los microservicios son para proyectos que van en crecimiento constante.
-Se tienen que hacer diferentes pruebas para cada servicio para ver si está funcionando correctamente, durante un tiempo.
- La seguridad  y velocidad va depender de la red que se esté usando.
- Obtener y convertir la información, también usará  más tiempo en el servidor, ya que tiene que recibir y convertir la información para los diferentes lenguajes que esten usando los servicios

¿Cómo garantizamos la disponibilidad de un servicio en la arquitectura basada en microservicios?
- Realizando las pruebas necesarias para verificar que todo esté en orden