# Práctica 1 - Parte 2

¿Qué lenguaje de programación utiliza el equipo de Netflix?
- Java Web

¿Qué sucedía con la base de datos de Oracle del monolito de Netflix?
- Solo era una pieza del hadware que ejecutaba una gran base de datos 

¿Cuál fue una de las principales desventajas que el equipo de Netflix tuvo con la arquitectura monolítica?
- Cuando tenían un error era dificil encontrar el origen y esto tomaba tiempo.
- Que necesitaban un hadware más grande para que pudieran escalar.

¿A qué autor cita el ponente cuando da el concepto de un microservicio?
- Martin Fowler.

¿Cuáles son las 3 principales ventajas que el ponente cita sobre los microservicios?
- Separación de procesos
- Escalabilidad (escala horizontal y particionando la carga de trabajo)
- Virtualización y escalabilidad 


¿Qué analogía se utiliza para comparar los microservicios con la vida real?
- Compara con Sistemas de órganos ya que cada órgano tiene un propósito y todos en si  forman un organismo.

Describe al menos 3 diferentes tipos de servicios que Netflix tenía en su arquitectura en aquel entonces
- Zul: es una capa que hace todas las posibles rutas de forma dinámica.
- NCCP : admitía dispositivos más recientes.
- API: permite que los servicios se comuniquen entre si y ejecuten las peticiones.
- Plataforma y nivel medio: es una combinación de servicios entre  la plataforma y nivel medio que permitían que dar una idea de como se ven los servicios (pruebas, las configuraciones y el almacenamiento de la información, etc).

¿Cuáles son las áreas primarias que se proponen para los retos y soluciones de utilizar microservicios?
- Cambios y soluciones:
-Dependencia
-escalabilidad 
-varianza

¿Qué es el falló en cascada?
- Es cuando un servicio falla  y los servicios que están conectados entre  si puede provocar que falle en otros servicios y esto provocar que todo deje de funcionar.

¿Qué es Hystrix?
- Es una estructura  para manejar los tiempos de espera como tipo respaldo y asi el cliente pueda seguir usando el servicio en vez de obtener un error.

¿Qué analogía utiliza el ponente para comparar las librerias de cliente con la vida real?
- La comparó con un parasito con la librería de cliente ya que aveces hacen cosas que no sabiamos que podría ocasionar y esto puede provocar muchas fallas en el sistea y pueden duplicarse y ocasionar más problemas.

¿De qué manera el equipo de Netflix manejo el problema de la persistencia en microservicios?
- Teorema de CAP dice que la presencia de una partición de red debe elegir entre la consistencua y la disponibilidad

¿Cuál fue la estrategia de Netflix después de que sufrieron la caída del 24 de Diciembre del 2012?
- La estrategia multiregional con tres regiones de en donde una fallaba , todavía podia funcionar.

¿Cuáles son los 3 escenarios/casos que se plantean para la parte de escalamiento?
- servicios stateless
- servicios estatales
- servicios híbridos

¿De qué manera se describe un "stateless service" en el video?
- Es una base de datos que no está almacenando información, y si se pierde un nodo no es un evento.

¿Qué es Chaos Monkey?
- Es cuando un nodo muere, todo sigue funcionando

¿Qué es un microservicio híbrido?
- Es una combinación entre servicios stateless y servicios estatales

¿Cómo solucionó el equipo de Netflix el problema con el anti-patrón de carga excesiva?
-  particionamiento de la carga de trabajo
-  almacenamiento en caché a nivel de solicitud
-  respaldo de token seguro

¿Qué tecnologías nuevas integró el equipo de Netflix cuando comenzó a manejar contenedores?
- Docker 
- node.js
- python
- Ruby

¿Cuáles fueron algunos de los principales costos de varianza del equipo de Netflix?
- herramientas de productividad
- capacidades de insight y triage
- fragancia de la imagen base
- gestión de nodos
- curva de aprendizaje - experiencia en producción


¿Qué es Spinnaker?
- una plataforma de entrega y entrega automatizada , que se administra en la nube

¿Cómo manejo Netflix el problema de las arquitecturas híbridas?
-  Primero  vieron las soluciones , luego el equipo que tenian , y refactorizaron los servicios  para respaldar mejor su arquitectura.

¿Qué es "chaos engineering" o "ingeniería del caos"?
- La Ingeniería del Caos es cuando hacen pruebas en un sistema, con el fin de ver la capacidad  aunque sean condiciones que puedan causar problemas en el  sistema cuando este en producción 