# EJERCICIO 5

En el ejercicio 5 lo primero que hice fue refactorizar el código donde se uso el Single Responsibility Principle:

Cada método tedra el nombre formato_"nombretipo" para definirl el tipo de documento donde cada función  recibe un formato y  se define el tipo  y retorna  la representación de cada uno, en el caso del metodo formato_html cambie json.dumps(self.__dict__) por el self.formato_json() ya que se repetia código y era mas simple entender si mandaba a llamar la función  ya que retornaba el mismo dato.

Realize unas pruebas unitarias para el archivo srp.py  donde se muestra la representación de como se veria la variable en  las diferentes sitiuaciones de representacion.

-¿Qué sucedería si quiero agregar otro formato de serialización más complejo como XML o Yaml?
    primero tendriamos que descargar primero la libreria json2xml para generar el xml:desúes se 
    importa, luego obtiene el xml de una cadena json y después retorna el xmml, en el caso del yaml también se tendria que buscar
    la librería que se usa para coonvertirlo en formato yaml y luego declarar un metodo con su respectiva operación para llegar a ese formato.
 
-¿Qué sucedería si quiero soporte para serialización a otros objetos aparte de los instanciados por la clase Usuario?
    identificar que patron se le acomodadaría mejor para hacerlo más sencillo, porque si seguimos agregando muchas instancias serían demasiadas y sería
    poco entendible.
