########################### INSERTAR Libro##################################

ins_lib = Libros.create(id_libro="1",nombre_libro="Cien años de soledad",nombre_autor="Gabriel ",editorial_libro=" Harper, Jonathan Cape")
ins_lib2 =Libros.create(id_libro="2",nombre_libro="El señor de los anillos",nombre_autor="J. R. R",editorial_libro="George allen & uniwin")
ins_lib3 =Libros.create(id_libro="3",nombre_libro="1984",nombre_autor="George",editorial_libro="Secker and Warburg")
ins_lib4 =Libros.create(id_libro="4",nombre_libro="Un mundo feliz",nombre_autor="Aldous Huxley",editorial_libro="Edhasa")
ins_lib5 =Libros.create(id_libro="5",nombre_libro="Orgullo y prejuicio",nombre_autor="ane Austen",editorial_libro="Austral")
ins_lib6 =Libros.create(id_libro="6",nombre_libro="Crimen y castigo",nombre_autor="Fiódor Dostoyevski",editorial_libro="Gredos")
ins_lib7 =Libros.create(id_libro="7",nombre_libro="Lolita",nombre_autor="Vladimir Nabokov",editorial_libro="Olympia Press")
ins_lib8 =Libros.create(id_libro="8",nombre_libro="Ulises",nombre_autor="James Joyce",editorial_libro="Sylvia Beach")
ins_lib9 =Libros.create(id_libro="9",nombre_libro="Madame Bovary",nombre_autor="Gustave Flaubert",editorial_libro="Madame Bovary")
ins_lib10=Libros.create(id_libro="10",nombre_libro="En busca del tiempo perdido",nombre_autor="Marcel Proust",editorial_libro="Éditions Grasset")
ins_lib11=Libros.create(id_libro="11",nombre_libro="Don Quijote de la Mancha",nombre_autor="Miguel de Cervantes",editorial_libro="Francisco de Robles")
ins_lib12 =Libros.create(id_libro="12",nombre_libro="El retrato de Dorian Gray",nombre_autor=" Oscar Wilde",editorial_libro="Austral")
ins_lib13 =Libros.create(id_libro="13",nombre_libro="Ana Karenina",nombre_autor=" León Tolstói",editorial_libro="Austral")
ins_lib14 =Libros.create(id_libro="14",nombre_libro="El Principito",nombre_autor="Antoine de Saint-Exupéry",editorial_libro="Océano Historias gráficas")
ins_lib15 =Libros.create(id_libro="15",nombre_libro="El proceso",nombre_autor="Franz Kafka",editorial_libro="DICIONES CATEDRA ")
ins_lib16 =Libros.create(id_libro="16",nombre_libro="El ruido y la furia",nombre_autor="William Faulkner",editorial_libro="DICIONES CATEDRA ")
ins_lib17 =Libros.create(id_libro="17",nombre_libro="Hamlet",nombre_autor="William Shakespeare",editorial_libro="DICIONES CATEDRA ")
ins_lib18 =Libros.create(id_libro="18",nombre_libro="Lo que el viento se llevó",nombre_autor="Margaret Mitchell",editorial_libro="PENGUIN RANDOM HOUSE GRUPO EDITORIAL ESPAÑA")
ins_lib19 =Libros.create(id_libro="19",nombre_libro="La Odisea",nombre_autor="Homero",editorial_libro="PORRUA ")
ins_lib20 =Libros.create(id_libro="20",nombre_libro="Las uvas de la ira",nombre_autor="John Steinbeck",editorial_libro="EDICIONES CATEDRA ")
ins_lib21 = Libros.create(id_libro="21",nombre_libro="El guardián entre el centeno",nombre_autor="J. D. Salinger",editorial_libro="ALIANZA EDITORIAL ")
ins_lib21 =Libros.create(id_libro="22",nombre_libro="Cumbres borrascosas",nombre_autor="Emily Brontë",editorial_libro="PORRUA ")
ins_lib23 =Libros.create(id_libro="23",nombre_libro="El gran Gatsby",nombre_autor="F. Scott Fitzgerald",editorial_libro="FONTAMARA ")
ins_lib24 =Libros.create(id_libro="24",nombre_libro="Mil soles espléndidos",nombre_autor="Khaled Hosseini",editorial_libro="OCEANO / SALAMANDRA ")
ins_lib25 =Libros.create(id_libro="25",nombre_libro="Alicia en el país de las maravillas",nombre_autor="Lewis Carroll",editorial_libro="Océano Historias gráficas")
ins_lib26 =Libros.create(id_libro="26",nombre_libro="Rebelión en la granja",nombre_autor="George Orwell",editorial_libro="EMU (EDITORES MEXICANOS UNIDOS) ")
ins_lib27 =Libros.create(id_libro="27",nombre_libro="Los pilares de la tierra",nombre_autor="Ken Follett",editorial_libro="ALIANZA EDITORIAL ")
ins_lib28 =Libros.create(id_libro="28",nombre_libro="Guerra y paz",nombre_autor="León Tolstói",editorial_libro="GRUPO EDITORIAL TOMO ")
ins_lib29 =Libros.create(id_libro="29",nombre_libro="Memorias de una geisha",nombre_autor="Arthur Golden",editorial_libro="DEBOLSILLO ")
ins_lib30 =Libros.create(id_libro="30",nombre_libro="Frankenstein",nombre_autor="Mary W. Shelley",editorial_libro="CASA EDITORIAL BOEK MEXICO ")
ins_lib31=Libros.create(id_libro="31",nombre_libro="Los viajes de Gulliver",nombre_autor="Jonathan Swift",editorial_libro=" PLUTON EDICIONES ")
ins_lib32 =Libros.create(id_libro="32",nombre_libro="La ladrona de libros",nombre_autor="Markus Zusak",editorial_libro="PENGUIN RANDOM HOUSE GRUPO EDITORIAL ESPAÑA")
ins_lib33 =Libros.create(id_libro="33",nombre_libro="Matar a un ruiseñor",nombre_autor="Harper Lee.",editorial_libro="HARPER COLLINS PUBLISHERS ")
ins_lib34 =Libros.create(id_libro="34",nombre_libro="El conde de Montecristo",nombre_autor="Alejandro Dumas",editorial_libro="PORRUA ")
ins_lib35 =Libros.create(id_libro="35",nombre_libro="Los juegos del hambre",nombre_autor=" Suzanne Collins",editorial_libro="OCEANO / TRAVESIA ")
ins_lib36 =Libros.create(id_libro="36",nombre_libro="Harry Potter y la piedra filosofal",nombre_autor="J. K. Rowling",editorial_libro="OCEANO / SALAMANDRA ")
ins_lib37 =Libros.create(id_libro="37",nombre_libro="El señor de las moscas",nombre_autor="William Golding",editorial_libro=" ALIANZA EDITORIAL ")
ins_lib38 =Libros.create(id_libro="38",nombre_libro="Moby Dick",nombre_autor=" Herman Melville",editorial_libro="EXODO ")
ins_lib39 =Libros.create(id_libro="39",nombre_libro="Los miserables",nombre_autor="Victor Hugo",editorial_libro="PORRUA")
ins_lib40 =Libros.create(id_libro="40",nombre_libro="Las aventuras de Huckleberry Finn",nombre_autor=" Mark Twain",editorial_libro="EPOCA INFANTIL ")
ins_lib41 = Libros.create(id_libro="41",nombre_libro="Tristam Shandy",nombre_autor="Laurence Sterne",editorial_libro="EDICIONES CATEDRA ")
ins_lib42 =Libros.create(id_libro="42",nombre_libro="Drácula",nombre_autor="Bram Stoker",editorial_libro="EDICIONES AVENTURA ")
ins_lib43 =Libros.create(id_libro="43",nombre_libro="El nombre de la rosa",nombre_autor="Umberto Eco",editorial_libro=" DEBOLSILLO ")
ins_lib44 =Libros.create(id_libro="44",nombre_libro="El extranjero",nombre_autor="Albert Camus",editorial_libro="BOOKET ")
ins_lib45 =Libros.create(id_libro="45",nombre_libro="Los hermanos Karamázov",nombre_autor="Fiódor Dostoyevski",editorial_libro=" PORRUA ")
ins_lib46 =Libros.create(id_libro="46",nombre_libro="El amor en los tiempos del cólera",nombre_autor="Gabriel García Márquez",editorial_libro="DIANA ")
ins_lib47 =Libros.create(id_libro="47",nombre_libro="Harry Potter y las reliquias de la muerte",nombre_autor="J. K. Rowling",editorial_libro=" OCEANO / SALAMANDRA ")
ins_lib48 =Libros.create(id_libro="48",nombre_libro="El código Da Vinci",nombre_autor="Dan Brown",editorial_libro=":SAL TERRAE")
ins_lib49 =Libros.create(id_libro="49",nombre_libro="Harry Potter y el prisionero de Azkaban",nombre_autor="J. K. Rowling",editorial_libro="OCEANO / SALAMANDRA ")
ins_lib50 =Libros.create(id_libro="50",nombre_libro="Cometas en el cielo",nombre_autor="Khaled Hosseini",editorial_libro="OCEANO / SALAMANDRA ")
ins_lib51 = Libros.create(id_libro="51",nombre_libro="Ensayo sobre la ceguera",nombre_autor="José Saramago",editorial_libro="DEBOLSILLO ")
ins_lib52 =Libros.create(id_libro="52",nombre_libro="Las crónicas de Narnia",nombre_autor="C. S. Lewis",editorial_libro=" DESTINO ")
ins_lib53 =Libros.create(id_libro="53",nombre_libro="Los renglones torcidos de Dios",nombre_autor="Torcuato Luca de Tena",editorial_libro="PLANETA ")
ins_lib54 =Libros.create(id_libro="54",nombre_libro="En llamas",nombre_autor="Suzanne Collins",editorial_libro="RBA LIBROS ")
ins_lib55 =Libros.create(id_libro="55",nombre_libro="Harry Potter y el cáliz de fuego",nombre_autor="J. K. Rowling",editorial_libro="OCEANO / SALAMANDRA ")
ins_lib56 =Libros.create(id_libro="56",nombre_libro="La sombra del viento",nombre_autor="Carlos Ruiz Zafón",editorial_libro="BOOKET ")
ins_lib57 =Libros.create(id_libro="57",nombre_libro="Viaje al fin de la noche",nombre_autor="Louis Ferdinand Céline",editorial_libro="EDHASA")
ins_lib58 =Libros.create(id_libro="58",nombre_libro="Harry Potter y el misterio del príncipe ",nombre_autor="J. K. Rowling",editorial_libro="OCEANO / SALAMANDRA ")
ins_lib59 =Libros.create(id_libro="59",nombre_libro="El juego de Ender",nombre_autor="Orson Scott Card",editorial_libro="EDICIONES B ")
ins_lib60 =Libros.create(id_libro="60",nombre_libro="La Biblia",nombre_autor="n/a",editorial_libro="SUD")
ins_lib61=Libros.create(id_libro="61",nombre_libro="La montaña mágica",nombre_autor="Thomas Mann",editorial_libro="MIRLO ")
ins_lib62 =Libros.create(id_libro="62",nombre_libro="Harry Potter y la Orden del Fénix",nombre_autor=" J. K. Rowling",editorial_libro="OCEANO / SALAMANDRA ")
ins_lib63 =Libros.create(id_libro="63",nombre_libro="El psicoanalista",nombre_autor="John Katzenbach",editorial_libro="MANANTIAL ")
ins_lib64 =Libros.create(id_libro="64",nombre_libro="Trampa 22",nombre_autor="Joseph Heller",editorial_libro="RBA / COLOFON ")
ins_lib65 =Libros.create(id_libro="65",nombre_libro="Por quién doblan las campanas",nombre_autor="Hernest Hemingway",editorial_libro="EPOCA ")
ins_lib66 =Libros.create(id_libro="66",nombre_libro="Dr. Jekyll y Mr. Hyde",nombre_autor="Robert Louis Stevenson",editorial_libro="FONTANA ")
ins_lib67 =Libros.create(id_libro="67",nombre_libro="El médico",nombre_autor="Noah Gordon",editorial_libro="ROCABOLSILLO")
ins_lib68 =Libros.create(id_libro="68",nombre_libro="La metamorfosis",nombre_autor="Franz Kafka",editorial_libro="PORRUA ")
ins_lib69 =Libros.create(id_libro="69",nombre_libro="La telaraña de Carlota",nombre_autor="E.B. White",editorial_libro="NOGUER INFANTIL ")
ins_lib70 =Libros.create(id_libro="70",nombre_libro="La divina comedia",nombre_autor="Dante Alighieri",editorial_libro="PORRUA ")
ins_lib71 = Libros.create(id_libro="71",nombre_libro="La señora Dalloway",nombre_autor="Virginia Woolf",editorial_libro="AKAL EDICIONES ")
ins_lib72 =Libros.create(id_libro="72",nombre_libro="Crepúsculo",nombre_autor="Stephenie Meyer",editorial_libro="DEBOLSILLO ")
ins_lib73 =Libros.create(id_libro="73",nombre_libro="En el camino",nombre_autor="Jack Kerouac",editorial_libro="Viking Press")
ins_lib74 =Libros.create(id_libro="74",nombre_libro="La Iliada",nombre_autor="Homero",editorial_libro="AKAL")
ins_lib75 =Libros.create(id_libro="75",nombre_libro="Jane Eyre",nombre_autor="Charlotte Brontë",editorial_libro="Smith, Elder & Co.")
ins_lib76 =Libros.create(id_libro="76",nombre_libro="Diario",nombre_autor="Ana Frank",editorial_libro="Alienta")
ins_lib77 =Libros.create(id_libro="77",nombre_libro="El retorno del Rey",nombre_autor="J.R.R. Tolkien",editorial_libro=" George Allen & Unwin")
ins_lib78 =Libros.create(id_libro="78",nombre_libro="El perfume",nombre_autor="Patrick Süskind",editorial_libro="‎Diogenes Verlag	")
ins_lib79 =Libros.create(id_libro="79",nombre_libro="Fahrenheit 451",nombre_autor="Ray Bradbury",editorial_libro="Ballantine Books")
ins_lib80 =Libros.create(id_libro="80",nombre_libro="Crónica de una muerte anunciada",nombre_autor="Gabriel García Márquez",editorial_libro="‎La Oveja Negra")
ins_lib81=Libros.create(id_libro="81",nombre_libro="La casa de los espíritus",nombre_autor="Isabel Allende",editorial_libro="DEBOLSILLO")
ins_lib82 =Libros.create(id_libro="82",nombre_libro="Mientras agonizo",nombre_autor="William Faulkner",editorial_libro="ALIANZA")
ins_lib83 =Libros.create(id_libro="83",nombre_libro="La isla del tesoro",nombre_autor="Robert Louis Stevenson",editorial_libro="Cassell")
ins_lib84 =Libros.create(id_libro="84",nombre_libro="Todo se desmorona",nombre_autor="Chinua Achebe",editorial_libro="Heinemann")
ins_lib85 =Libros.create(id_libro="85",nombre_libro="Emma",nombre_autor="Jane Austen",editorial_libro="ALIANZA")
ins_lib86 =Libros.create(id_libro="86",nombre_libro="Pasaje a la India",nombre_autor="E. M. Forster",editorial_libro="Edward Arnold")
ins_lib87 =Libros.create(id_libro="87",nombre_libro="Ficciones",nombre_autor="Jorge Luis Borges",editorial_libro="Emecé Editores")
ins_lib88 =Libros.create(id_libro="88",nombre_libro="Harry Potter y la cámara secreta",nombre_autor="J. K. Rowling",editorial_libro=" OCEANO / SALAMANDRA ")
ins_lib89 =Libros.create(id_libro="89",nombre_libro="A sangre fría",nombre_autor="Truman Capote",editorial_libro="Penguin Random House Grupo Editorial")
ins_lib90 =Libros.create(id_libro="90",nombre_libro="Rimas y leyendas",nombre_autor="Gustavo Adolfo Bécquer",editorial_libro="ALFAGUARA")
ins_lib91 = Libros.create(id_libro="91",nombre_libro="El corazón es un cazador solitario",nombre_autor="Carson Mccullers",editorial_libro="Houghton Mifflin Harcourt")
ins_lib92 =Libros.create(id_libro="92",nombre_libro="El Rey Lear",nombre_autor="William Shakespear",editorial_libro=" Austral")
ins_lib93 =Libros.create(id_libro="93",nombre_libro="Tormenta de espadas",nombre_autor="George R.R. Martin",editorial_libro="GIGAMESH")
ins_lib94 =Libros.create(id_libro="94",nombre_libro="Juego de tronos",nombre_autor="George R.R.Martin",editorial_libro="PLANETA")
ins_lib95 =Libros.create(id_libro="95",nombre_libro="La catedral del mar",nombre_autor="Ildefonso Falcones",editorial_libro="GRIJALBO")
ins_lib96 =Libros.create(id_libro="96",nombre_libro="Progreso del peregrino",nombre_autor="John Bunyan",editorial_libro="Whitaker House")
ins_lib97 =Libros.create(id_libro="97",nombre_libro="El corazón de las tinieblas",nombre_autor="Joseph Conrad",editorial_libro="JUVENTUD")
ins_lib98 =Libros.create(id_libro="98",nombre_libro="Robinson Crusoe",nombre_autor="Daniel Defoe",editorial_libro=" W. Taylo")
ins_lib99 =Libros.create(id_libro="99",nombre_libro="La isla de los amores infinitos",nombre_autor="Daína Chaviano",editorial_libro="DEBOLSILLO")
ins_lib100 =Libros.create(id_libro="100",nombre_libro="David Copperfield",nombre_autor="Charles Dickens",editorial_libro="Bradbury and Evans")

########################### INSERTAR Autores #################################
ins_au = Autores.create(id_autor="1",nombre_autor="Gabriel ",apellido_autor="García Márquez")
ins_lib2 =Autores.create(id_autor="2",nombre_autor="J. R. R. ",apellido_autor="Tolkien")
ins_lib3 =Autores.create(id_autor="3",nombre_autor="George",apellido_autor=" Orwell")
ins_lib4 =Autores.create(id_autor="4",nombre_autor="Aldous",apellido_autor="Huxley")
ins_lib5 =Autores.create(id_autor="5",nombre_autor=" Jane ",apellido_autor="Austen")
ins_lib6 =Autores.create(id_autor="6",nombre_autor="Fiódor",apellido_autor=" Dostoyevski")
ins_lib7 =Autores.create(id_autor="7",nombre_autor="Vladimir",apellido_autor="Nabokov")
ins_lib8 =Autores.create(id_autor="8",nombre_autor="James",apellido_autor="Joyce")
ins_lib9 =Autores.create(id_autor="9",nombre_autor="Gustave",apellido_autor="Flaubert")
ins_lib10 =Autores.create(id_autor="10",nombre_autor=" Marcel",apellido_autor="Proust")
ins_lib11 =Autores.create(id_autor="11",nombre_autor="Miguel",apellido_autor=" Cervantes")
ins_lib12 =Autores.create(id_autor="12",nombre_autor="Oscar",apellido_autor="Wilde")
ins_lib13 =Autores.create(id_autor="13",nombre_autor="León",apellido_autor="Tolstói")
ins_lib14 =Autores.create(id_autor="14",nombre_autor="Antoine",apellido_autor="Saint-Exupéry")
ins_lib15 =Autores.create(id_autor="15",nombre_autor="Franz",apellido_autor="Kafka")
ins_lib16 =Autores.create(id_autor="16",nombre_autor="William",apellido_autor="Faulkner")
ins_lib17 =Autores.create(id_autor="17",nombre_autor="William",apellido_autor="Shakespeare")
ins_lib18 =Autores.create(id_autor="18",nombre_autor="Margaret",apellido_autor="Mitchell")
ins_lib19 =Autores.create(id_autor="19",nombre_autor="Homero",apellido_autor="")
ins_lib20 =Autores.create(id_autor="20",nombre_autor=" John",apellido_autor="Steinbeck")
ins_lib21 =Autores.create(id_autor="21",nombre_autor="J. D",apellido_autor="Salinger")
ins_lib22 =Autores.create(id_autor="22",nombre_autor="Emily",apellido_autor="Brontë")
ins_lib23 =Autores.create(id_autor="23",nombre_autor=" F.",apellido_autor="Scott Fitzgerald.")
ins_lib24 =Autores.create(id_autor="24",nombre_autor="Khaled",apellido_autor="Hosseini")
ins_lib25 =Autores.create(id_autor="25",nombre_autor="Lewis",apellido_autor="Carroll")
ins_lib26 =Autores.create(id_autor="26",nombre_autor="George",apellido_autor="Orwell")
ins_lib27 =Autores.create(id_autor="27",nombre_autor="Ken",apellido_autor="Follett")
ins_lib28 =Autores.create(id_autor="28",nombre_autor="León",apellido_autor="Tolstói")
ins_lib29 =Autores.create(id_autor="29",nombre_autor="Arthur",apellido_autor="Golden")
ins_lib30 =Autores.create(id_autor="30",nombre_autor="Mary",apellido_autor="W. Shelley")
ins_lib31 =Autores.create(id_autor="31",nombre_autor="Jonathan",apellido_autor="Swift")
ins_lib32 =Autores.create(id_autor="32",nombre_autor="Markus",apellido_autor="Zusak")
ins_lib33 =Autores.create(id_autor="33",nombre_autor="Harper",apellido_autor="Lee")
ins_lib34 =Autores.create(id_autor="34",nombre_autor="Alejandro",apellido_autor="Dumas")
ins_lib35 =Autores.create(id_autor="35",nombre_autor="Suzanne",apellido_autor="Collins")
ins_lib35 =Autores.create(id_autor="35",nombre_autor=" J. K",apellido_autor="Rowling.")
ins_lib36 =Autores.create(id_autor="36",nombre_autor="William",apellido_autor="Golding")
ins_lib37 =Autores.create(id_autor="37",nombre_autor="Herman",apellido_autor="Melville")
ins_lib38 =Autores.create(id_autor="38",nombre_autor="Victor ",apellido_autor="Hugo")
ins_lib39 =Autores.create(id_autor="39",nombre_autor="Mark",apellido_autor="Twain")
ins_lib40 =Autores.create(id_autor="40",nombre_autor="Laurence",apellido_autor="Sterne")
ins_lib41 =Autores.create(id_autor="41",nombre_autor="Bram",apellido_autor="Stoker")
ins_lib42 =Autores.create(id_autor="42",nombre_autor="Umberto",apellido_autor="Eco")
ins_lib43 =Autores.create(id_autor="43",nombre_autor="Albert",apellido_autor="Camus")
ins_lib44 =Autores.create(id_autor="44",nombre_autor="Fiódor",apellido_autor="Dostoyevski")
ins_lib45 =Autores.create(id_autor="45",nombre_autor="Gabriel",apellido_autor="García Márquez")
ins_lib46 =Autores.create(id_autor="46",nombre_autor="Dan",apellido_autor="Brown")
ins_lib47 =Autores.create(id_autor="47",nombre_autor="Khaled",apellido_autor="Hosseini")
ins_lib48 =Autores.create(id_autor="48",nombre_autor="José",apellido_autor="Saramago")
ins_lib49 =Autores.create(id_autor="49",nombre_autor="C. S",apellido_autor="Lewis")
ins_lib50 =Autores.create(id_autor="50",nombre_autor="Torcuato",apellido_autor="Luca de Tena")
ins_lib51 =Autores.create(id_autor="51",nombre_autor="Suzanne",apellido_autor="Collins")
ins_lib52 =Autores.create(id_autor="52",nombre_autor="Carlos",apellido_autor="Ruiz Zafón")
ins_lib53 =Autores.create(id_autor="53",nombre_autor="Louis",apellido_autor="Ferdinand Céline")
ins_lib54 =Autores.create(id_autor="54",nombre_autor="Orson",apellido_autor="Scott Card")
ins_lib55 =Autores.create(id_autor="55",nombre_autor="Thomas",apellido_autor="Mann")
ins_lib56 =Autores.create(id_autor="56",nombre_autor="John",apellido_autor="Katzenbach")
ins_lib57 =Autores.create(id_autor="57",nombre_autor="Joseph",apellido_autor="Heller")
ins_lib58 =Autores.create(id_autor="58",nombre_autor="Hernest",apellido_autor="Hemingway")
ins_lib59 =Autores.create(id_autor="59",nombre_autor="Robert",apellido_autor="Louis Stevenson")
ins_lib60 =Autores.create(id_autor="60",nombre_autor="Noah",apellido_autor="Gordon")
ins_lib61 =Autores.create(id_autor="61",nombre_autor="Franz",apellido_autor="Kafka")
ins_lib62 =Autores.create(id_autor="62",nombre_autor="E.B",apellido_autor="White")
ins_lib63 =Autores.create(id_autor="63",nombre_autor="Dante",apellido_autor="Alighieri")
ins_lib64 =Autores.create(id_autor="64",nombre_autor="Virginia",apellido_autor="Woolf")
ins_lib65 =Autores.create(id_autor="65",nombre_autor="Stephenie",apellido_autor="Meyer")
ins_lib66 =Autores.create(id_autor="66",nombre_autor="Jack",apellido_autor="Kerouac")
ins_lib67 =Autores.create(id_autor="67",nombre_autor="Charlotte",apellido_autor=" Brontë")
ins_lib68 =Autores.create(id_autor="68",nombre_autor="Ana",apellido_autor="Frank")
ins_lib69 =Autores.create(id_autor="69",nombre_autor="J.R.R.",apellido_autor="Tolkien")
ins_lib70 =Autores.create(id_autor="70",nombre_autor="Patrick",apellido_autor="Süskind")
ins_lib71 =Autores.create(id_autor="71",nombre_autor="Ray",apellido_autor="Bradbury.")
ins_lib72 =Autores.create(id_autor="72",nombre_autor=" Gabriel",apellido_autor="García Márquez")
ins_lib73 =Autores.create(id_autor="73",nombre_autor="Isabel",apellido_autor="Allende")
ins_lib74 =Autores.create(id_autor="74",nombre_autor="William",apellido_autor="Faulkner")
ins_lib75 =Autores.create(id_autor="75",nombre_autor="Robert",apellido_autor="Louis Stevenson")
ins_lib76 =Autores.create(id_autor="76",nombre_autor="Chinua",apellido_autor="Achebe")
ins_lib77 =Autores.create(id_autor="77",nombre_autor="Jane",apellido_autor="Austen")
ins_lib78 =Autores.create(id_autor="78",nombre_autor="E. M",apellido_autor="Forster")
ins_lib79 =Autores.create(id_autor="79",nombre_autor="Jorge",apellido_autor="Luis Borges")
ins_lib80 =Autores.create(id_autor="80",nombre_autor="Truman",apellido_autor="Capote")
ins_lib81 =Autores.create(id_autor="81",nombre_autor=" Gustavo",apellido_autor="Adolfo Bécquer")
ins_lib82 =Autores.create(id_autor="82",nombre_autor="Carson",apellido_autor="Mccullers")
ins_lib83 =Autores.create(id_autor="83",nombre_autor="George",apellido_autor="R.R. Martin")
ins_lib84 =Autores.create(id_autor="84",nombre_autor="Ildefonso",apellido_autor="Falcones")
ins_lib85 =Autores.create(id_autor="85",nombre_autor="John",apellido_autor="Bunyan")
ins_lib86 =Autores.create(id_autor="86",nombre_autor="Joseph",apellido_autor="Conrad")
ins_lib87 =Autores.create(id_autor="87",nombre_autor="Daniel",apellido_autor="Defoe")
ins_lib88 =Autores.create(id_autor="88",nombre_autor="Daína",apellido_autor="Chaviano")
ins_lib89 =Autores.create(id_autor="89",nombre_autor="Charles",apellido_autor="Dickens")
ins_lib90 =Autores.create(id_autor="90",nombre_autor="Hans",apellido_autor="Chrisian")
ins_lib91 =Autores.create(id_autor="91",nombre_autor="Jorge",apellido_autor="Luis")
ins_lib92 =Autores.create(id_autor="92",nombre_autor="Wolfgang",apellido_autor="Von")
ins_lib93 =Autores.create(id_autor="93",nombre_autor="Gunter",apellido_autor="Grass")
ins_lib94 =Autores.create(id_autor="94",nombre_autor="Knut",apellido_autor="Hamsun")
ins_lib95 =Autores.create(id_autor="95",nombre_autor="Lu",apellido_autor="Xun")
ins_lib96=Autores.create(id_autor="96",nombre_autor="Edgar",apellido_autor="Allan Poe")
ins_lib97=Autores.create(id_autor="97",nombre_autor="Jose",apellido_autor="Saramago")
ins_lib98=Autores.create(id_autor="98",nombre_autor="Leo",apellido_autor="Tolstoy")
ins_lib99=Autores.create(id_autor="99",nombre_autor="Elsa",apellido_autor="Morante")
ins_lib100=Autores.create(id_autor="100",nombre_autor="Aldous",apellido_autor="Huxley")

########################### INSERTAR Editoriales #################################
ins_ed1=Editoriales.create(id_editorial="1",editorial=" Harper, Jonathan Cape",pais_editrial="Reino Unido")
ins_ed2=Editoriales.create(id_editorial="2",editorial="George Allen & Unwin",pais_editrial="Reino Unido")
ins_ed3=Editoriales.create(id_editorial="3",editorial="Secker and Warburg",pais_editrial="Reino Unido")
ins_ed4=Editoriales.create(id_editorial="4",editorial="Edhasa",pais_editrial="Reino Unido")
ins_ed5=Editoriales.create(id_editorial="5",editorial="Austral",pais_editrial="España")
ins_ed6=Editoriales.create(id_editorial="6",editorial="Gredos",pais_editrial="Ruso")
ins_ed7=Editoriales.create(id_editorial="7",editorial="Olympia Press",pais_editrial="Francia")
ins_ed8=Editoriales.create(id_editorial="8",editorial="Sylvia Beach",pais_editrial="Paris")
ins_ed9=Editoriales.create(id_editorial="9",editorial="Madame Bovary",pais_editrial="Francia")
ins_ed10=Editoriales.create(id_editorial="10",editorial="Éditions Grasset",pais_editrial="Francia")
ins_ed11=Editoriales.create(id_editorial="11",editorial="Francisco de Robles",pais_editrial="España")
ins_ed12=Editoriales.create(id_editorial="12",editorial="Austral",pais_editrial="Irlanda")
ins_ed13=Editoriales.create(id_editorial="13",editorial="Océano Historias gráficas",pais_editrial="Mexico")
ins_ed14=Editoriales.create(id_editorial="14",editorial="DICIONES CATEDRA ",pais_editrial="España")
ins_ed15=Editoriales.create(id_editorial="15",editorial="PENGUIN RANDOM HOUSE GRUPO EDITORIAL ESPAÑA",pais_editrial="ESPAÑA")
ins_ed16=Editoriales.create(id_editorial="16",editorial="EMU (EDITORES MEXICANOS UNIDOS) ",pais_editrial="Ciudad de mexico")
ins_ed17=Editoriales.create(id_editorial="17",editorial="PORRUA ",pais_editrial="ciudad de mexico")
ins_ed18=Editoriales.create(id_editorial="18",editorial="EDICIONES CATEDRA ",pais_editrial="ESPAÑA")
ins_ed19=Editoriales.create(id_editorial="19",editorial="ALIANZA EDITORIAL ",pais_editrial="ESPAÑA")
ins_ed20=Editoriales.create(id_editorial="20",editorial="GRUPO EDITORIAL TOMO ",pais_editrial="ciudad de mexico")
ins_ed21=Editoriales.create(id_editorial="21",editorial="DEBOLSILLO ",pais_editrial="Ciudad de mexico")
ins_ed22=Editoriales.create(id_editorial="22",editorial="CASA EDITORIAL BOEK MEXICO ",pais_editrial="ciudad de mexico")
ins_ed23=Editoriales.create(id_editorial="23",editorial="PLUTON EDICIONES ",pais_editrial="Mexico")
ins_ed24=Editoriales.create(id_editorial="24",editorial="HARPER COLLINS PUBLISHERS ",pais_editrial="New York")
ins_ed25=Editoriales.create(id_editorial="25",editorial="PORRUA ",pais_editrial="Mexico")
ins_ed26=Editoriales.create(id_editorial="26",editorial="OCEANO / TRAVESIA ",pais_editrial="Mexico")
ins_ed27=Editoriales.create(id_editorial="27",editorial="OCEANO / SALAMANDRA ",pais_editrial="ESPAÑA")
ins_ed28=Editoriales.create(id_editorial="28",editorial=" ALIANZA EDITORIAL ",pais_editrial="ESPAÑA")
ins_ed29=Editoriales.create(id_editorial="29",editorial="EXODO ",pais_editrial="MEXICO")
ins_ed30=Editoriales.create(id_editorial="30",editorial="EPOCA INFANTIL ",pais_editrial="MEXICO")
ins_ed31=Editoriales.create(id_editorial="31",editorial="FONTAMARA ",pais_editrial="MEXICO")
ins_ed32=Editoriales.create(id_editorial="32",editorial="EDICIONES CATEDRA ",pais_editrial="ESPAÑA")
ins_ed33=Editoriales.create(id_editorial="33",editorial=" EDICIONES AVENTURA ",pais_editrial="ESPAÑA")
ins_ed34=Editoriales.create(id_editorial="34",editorial="BOOKET ",pais_editrial="MEXICO")
ins_ed35=Editoriales.create(id_editorial="35",editorial="DIANA ",pais_editrial="MEXICO")
ins_ed36=Editoriales.create(id_editorial="36",editorial="SAL TERRAE",pais_editrial="CHILE")
ins_ed37=Editoriales.create(id_editorial="37",editorial="DESTINO ",pais_editrial="ESPAÑA")
ins_ed38=Editoriales.create(id_editorial="38",editorial="PLANETA ",pais_editrial="ESPAÑA")
ins_ed39=Editoriales.create(id_editorial="39",editorial=" RBA LIBROS ",pais_editrial="MEXICO")
ins_ed40=Editoriales.create(id_editorial="40",editorial="EDHASA",pais_editrial="ARGENTINA")
ins_ed41=Editoriales.create(id_editorial="41",editorial="SUD",pais_editrial="España")
ins_ed42=Editoriales.create(id_editorial="42",editorial="EDICIONES B ",pais_editrial="ESPAÑA")
ins_ed43=Editoriales.create(id_editorial="43",editorial="MIRLO ",pais_editrial="mexico")
ins_ed44=Editoriales.create(id_editorial="44",editorial="MANANTIAL ",pais_editrial="Argentina")
ins_ed45=Editoriales.create(id_editorial="45",editorial="RBA / COLOFON ",pais_editrial="España")
ins_ed45=Editoriales.create(id_editorial="46",editorial="EPOCA ",pais_editrial="ESPAÑA")
ins_ed47=Editoriales.create(id_editorial="47",editorial="ROCABOLSILLO",pais_editrial="ARGENTINA")
ins_ed48=Editoriales.create(id_editorial="48",editorial="FONTANA ",pais_editrial="ARGENTINA")
ins_ed49=Editoriales.create(id_editorial="49",editorial="NOGUER INFANTIL ",pais_editrial="CHILE")
ins_ed50=Editoriales.create(id_editorial="50",editorial="AKAL EDICIONES ",pais_editrial="MEXICO")
ins_ed51=Editoriales.create(id_editorial="51",editorial="Viking Press",pais_editrial="New York")
ins_ed52=Editoriales.create(id_editorial="52",editorial="Smith, Elder & Co.",pais_editrial="Reyno unido")
ins_ed53=Editoriales.create(id_editorial="53",editorial="Alienta",pais_editrial="España")
ins_ed54=Editoriales.create(id_editorial="54",editorial="‎Diogenes Verlag",pais_editrial="Alemania")
ins_ed55=Editoriales.create(id_editorial="55",editorial="Ballantine Books",pais_editrial="New York")
ins_ed56=Editoriales.create(id_editorial="56",editorial="‎La Oveja Negra",pais_editrial="Colombia")
ins_ed57=Editoriales.create(id_editorial="57",editorial="Cassell",pais_editrial="Reino unido")
ins_ed58=Editoriales.create(id_editorial="58",editorial="Heinemann",pais_editrial="Estados Unidos")
ins_ed59=Editoriales.create(id_editorial="59",editorial="Edward Arnold",pais_editrial="New York")
ins_ed60=Editoriales.create(id_editorial="60",editorial="Emecé Editores",pais_editrial="Buenos aires")
ins_ed61=Editoriales.create(id_editorial="61",editorial="Penguin Random House Grupo Editorial",pais_editrial="New York")
ins_ed62=Editoriales.create(id_editorial="62",editorial="ALFAGUARA",pais_editrial="ESPAÑA")
ins_ed63=Editoriales.create(id_editorial="63",editorial="Houghton Mifflin Harcourt",pais_editrial="Estados Unidos")
ins_ed64=Editoriales.create(id_editorial="64",editorial="Austral",pais_editrial="Buenos Aires")
ins_ed65=Editoriales.create(id_editorial="65",editorial="GIGAMESH",pais_editrial="España")
ins_ed66=Editoriales.create(id_editorial="66",editorial="PLANETA",pais_editrial="Mexico")
ins_ed67=Editoriales.create(id_editorial="67",editorial="GRIJALBO",pais_editrial="Mexico")
ins_ed68=Editoriales.create(id_editorial="68",editorial="Whitaker House",pais_editrial="España")
ins_ed69=Editoriales.create(id_editorial="69",editorial="JUVENTUD",pais_editrial="Mexico")
ins_ed70=Editoriales.create(id_editorial="70",editorial=" ‎W. Taylo",pais_editrial="Reino unido")
ins_ed71=Editoriales.create(id_editorial="71",editorial="Bradbury and Evans",pais_editrial="Reino unido")
ins_ed72=Editoriales.create(id_editorial="72",editorial="Almadía",pais_editrial="Mexico")
ins_ed73=Editoriales.create(id_editorial="73",editorial="EDITORIAL ESFINGE",pais_editrial="mexico")
ins_ed74=Editoriales.create(id_editorial="74",editorial="ESTACIÓN DE LECTURA",pais_editrial="mexico")
ins_ed75=Editoriales.create(id_editorial="75",editorial="NORIEGA EDITORES",pais_editrial="mexico")
ins_ed76=Editoriales.create(id_editorial="76",editorial="FONDO DE CULTURA ECONOMICA",pais_editrial="mexico")
ins_ed77=Editoriales.create(id_editorial="77",editorial="EDUCAL",pais_editrial="mexico")
ins_ed78=Editoriales.create(id_editorial="78",editorial="PAX MÉXICO",pais_editrial="mexico")
ins_ed79=Editoriales.create(id_editorial="79",editorial="ARI/TIPS EN FICHAS",pais_editrial="mexico")
ins_ed80=Editoriales.create(id_editorial="80",editorial="CEAC",pais_editrial="mexico")
ins_ed81=Editoriales.create(id_editorial="81",editorial="EDITORIAL DE VECCHI",pais_editrial="mexico")
ins_ed82=Editoriales.create(id_editorial="82",editorial="LECTORUM",pais_editrial="mexico")
ins_ed83=Editoriales.create(id_editorial="83",editorial="MCGRAW-HILL INTERAMERICANA",pais_editrial="mexico")
ins_ed84=Editoriales.create(id_editorial="84",editorial="EDICIONES FISCALES ISEF",pais_editrial="mexico")
ins_ed85=Editoriales.create(id_editorial="85",editorial="BANCRY-MACCHI",pais_editrial="mexico")
ins_ed86=Editoriales.create(id_editorial="86",editorial="MIGUEL ÁNGEL PORRÚA",pais_editrial="mexico")
ins_ed87=Editoriales.create(id_editorial="87",editorial="SAN PABLO",pais_editrial="mexico")
ins_ed88=Editoriales.create(id_editorial="88",editorial="EDICIONES SM",pais_editrial="mexico")
ins_ed89=Editoriales.create(id_editorial="89",editorial="EDICIONES LAROUSSE",pais_editrial="mexico")
ins_ed90=Editoriales.create(id_editorial="90",editorial="EDITORES MEXICANOS UNIDOS",pais_editrial="mexico")
ins_ed91=Editoriales.create(id_editorial="91",editorial="PARCIFAL EDICIONES",pais_editrial="mexico")
ins_ed92=Editoriales.create(id_editorial="92",editorial="EDICIONES URANO",pais_editrial="mexico")
ins_ed93=Editoriales.create(id_editorial="93",editorial="ALFAOMEGA GRUPO EDITOR",pais_editrial="mexico")
ins_ed94=Editoriales.create(id_editorial="94",editorial="CALIGRAMA EDITORES",pais_editrial="mexico")
ins_ed95=Editoriales.create(id_editorial="95",editorial="SANTILLANA",pais_editrial="mexico")
ins_ed96=Editoriales.create(id_editorial="96",editorial="PORRÚA",pais_editrial="mexico")
ins_ed97=Editoriales.create(id_editorial="97",editorial="PRELUDIO",pais_editrial="mexico")
ins_ed98=Editoriales.create(id_editorial="98",editorial="RICHMOND",pais_editrial="mexico")
ins_ed99=Editoriales.create(id_editorial="99",editorial="LIBROS IMAGINAR (INFANTIL",pais_editrial="mexico")
ins_ed100=Editoriales.create(id_editorial="100",editorial="UNAM",pais_editrial="mexico")
