# EJERCICIO 1

En el ejercicio 1 lo primero que hice fue:

Crear la Clase Paginaweb, que recibía los siguientes parámetros url, ruta, formato, contenido, titulo, slug, meta_tags y el la función __str__ describe como se presentarán los datos.

Luego cree la Clase SitioWeb en la funcion __init__ recibe el dominio, la categoría y la página que va se de tipo PaginaWeb, en la función __str__ describe como se presentarán los datos, por último imprimi el sitio_web.


## Estructura
- PaginaWeb: clase que representa un documento que se puede mostrar en un navegador web.
- SitioWeb: clase que representa una colección de páginas web que se agrupan.
- Cliente: el cliente declara primero la pagina_1 y pagina_2 donde se inicializa con la clase  PaginaWeb y ahi ingresa los datos según la estructura que espera que tenga.Luego crea un sitio_web que se inicializa con la clase SitioWeb donde se le agrego  un dominio, una categoría y las páginas que tiene, en la paginas le agregue las que declare ya que la página está inicializada en la clase SitioWeb y es de tipo PaginaWeb 