# EJERCICIO 3
## Facade

En el ejercicio 3 trata de implementar el patrón facade a partir de el facade_test.py sin modificarlo.En ese archivo importan la clase LavadoraFacade, y en el test vienen dos posibles casos que se el ciclo completo y el solo centrifugado.

Lo primero que hice fue crear el documento facade.py y cree la clase LavadoraFacade donde ahí se usa para saber la funcionalidad de los subistemas.
Luego cree los Subsistemas que se iban a utilizar en este caso Lavadora_Ciclo_Completo y Lavadora_Solo_Centrifugado y donde se agregó las respectivas funciones que se necesitarian segun el caso. Ya por último cree el cliente en el archivo facade.py antes de hacer las pruebas para ver que información me tría, después de ver lo que mostró corrí el test y pasarón las pruebas que venían desde un principio.

## Estructura
- LavadoraFacade: lo que se hace ahi es primero inicializar los atributos, en el cual en este caso fue  self.lav_ciclo_completo donde iba a ser igual al subsistema  Lavadora_Ciclo_Completo y  self.lav_solo_centrifugado se igualó a Lavadora_Solo_Centrifugado y luego declare 2  funciones que en el test mencionaban en este caso ciclo_completo y solo_centrifugado,  en cada una se declara el método que tendrá cada variable inicializada.

- Lavadora_Ciclo_Completo: Aquí declare la función ciclo_completo() que se declaró en la clase LavadoraFacade ahi va implentar lo que se mostrará al utilizar  el ciclo completo.

- Lavadora_Solo_Centrifugado: Aquí declare la función solo_centrifugado() que se declaró en la clase LavadoraFacade ahi va implentar lo que se mostrará al utilizar  solo el centrifugado.

- Cliente: el cliente decide que parte de los subistemas se va a ejecutar.

