version: "3.2"
services:
  db:
    image: postgres:9.4
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - postgresql
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "data.json"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    container_name:  pgadmin4_B
    environment:
      PGADMIN_DEFAULT_EMAIL: "data@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    ports:
     - "80:80"
    links:
     - db
    networks:
      - postgresql
    depends_on:
     - db

  app:
    build: ./app
    container_name: App_D
    restart: always
    links:
        - db
    ports:
        - "5000:5000"
    networks:
      - postgresql
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    command: ["python", "./app.py"]
    depends_on:
     - data.json
