version: "3.7"
services:
    mongodb:
        container_name: mongo_db
        image: mongo:4.4
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: Raul
            MONGO_INITDB_ROOT_PASSWORD: 14789pswd
            MONGO_INITDB_DATABASE: 2doPar

        volumes:
          - volumeMongo:/var/lib/docker/volumes/mongoVolume/_data

    mongo-express:
        container_name: dbms
        image: mongo-express
        restart: always
        ports:
            - "8082:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb

            ME_CONFIG_MONGODB_ADMINUSERNAME: Raul
            ME_CONFIG_MONGODB_ADMINPASSWORD: 14789pswd

            ME_CONFIG_BASICAUTH_USERNAME: Raul
            ME_CONFIG_BASICAUTH_PASSWORD: 14789pswd
            
volumes:
    volumeMongo: