from re import A
from flask import Flask, jsonify, request
import pymongo
client= pymongo.MongoClient("mongodb://root:s123@mongo_compose:27017/")
db=client["mi-db"]
coll=db["issues"]

app= Flask(__name__)

@app.route('/')
def issues():
    a_1= coll.find_one({'_id':'1'})
    a_2= coll.find_one({'_id':'2'})
    a_3= coll.find_one({'_id':'3'})
    a_4= coll.find_one({'_id':'4'})
    a_5= coll.find_one({'_id':'5'})
    a_6= coll.find_one({'_id':'6'})
    a_7= coll.find_one({'_id':'7'})
    a_8= coll.find_one({'_id':'8'})
    a_9= coll.find_one({'_id':'9'})
    a_10= coll.find_one({'_id':'10'})
    a_11= coll.find_one({'_id':'11'})
    a_12= coll.find_one({'_id':'12'})
    a_13= coll.find_one({'_id':'13'})

    b='<table class="issues">format <tr> <td>_ip</td> <td>url</td> <td>ver la pagina </td> </tr> <tr> <td> '+ str(a_1['_id'])+' </td> <td> '+ str(a_1['url'])+' </td> <td><p>pagina web <a href="/1">here</a><br /></p></td> </tr> <tr> <td> '+ str(a_2['_id'])+' </td> <td> '+ str(a_2['url'])+' </td> <td><p>pagina web <a href="/2">here</a><br /></p></td> </tr> <tr> <td> '+ str(a_3['_id'])+' </td> <td> '+ str(a_3['url'])+' </td> <td><p>pagina web <a href="/3">here</a><br /></p></td> </tr> <tr> <td> '+ str(a_4['_id'])+' </td> <td> '+ str(a_4['url'])+' </td> <td><p>pagina web <a href="/4">aqui</a><br /></p></td> </tr> <tr> <td> '+ str(a_5['_id'])+' </td> <td> '+ str(a_5['url'])+' </td> <td><p>pagina web <a href="/5">here</a><br /></p></td> </tr> <tr> <td> '+ str(a_6['_id'])+' </td> <td> '+ str(a_6['url'])+' </td> <td><p>pagina web <a href="/6">here</a><br /></p></td> </tr> <tr> <td> '+ str(a_7['_id'])+' </td> <td> '+ str(a_7['url'])+' </td> <td><p>pagina web <a href="/7">here</a><br /></p></td> </tr> <tr> <td> '+ str(a_8['_id'])+' </td> <td> '+ str(a_8['url'])+' </td> <td><p>pagina web <a href="/8">here</a><br /></p></td> </tr> <tr> <td> '+ str(a_9['_id'])+' </td> <td> '+ str(a_9['url'])+' </td> <td><p>pagina web <a href="/9">here</a><br /></p></td> </tr> <tr> <td> '+ str(a_10['_id'])+' </td> <td> '+ str(a_10['url'])+' </td> <td><p>pagina web <a href="/10">here</a><br /></p></td> </tr> <tr> <td> '+ str(a_11['_id'])+' </td> <td> '+ str(a_11['url'])+' </td> <td><p>pagina web <a href="/11">here</a><br /></p></td> </tr> <tr> <td> '+ str(a_12['_id'])+' </td> <td> '+ str(a_12['url'])+' </td> <td><p>pagina web <a href="/12">here</a><br /></p></td> <tr> <td> '+ str(a_13['_id'])+' </td> <td> '+ str(a_13['url'])+' </td> <td><p>pagina web <a href="/13">here</a><br /></p></td> </tr> </tr> </table>'
    return b 

@app.route('/1')
def issues1():
    a=coll.find_one({'_id':'1'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b
@app.route('/2')
def issues2():
    a=coll.find_one({'_id':'2'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b
@app.route('/3')
def issues3():
    a=coll.find_one({'_id':'3'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b

@app.route('/4')
def issues4():
    a=coll.find_one({'_id':'4'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b

@app.route('/5')
def issues5():
    a=coll.find_one({'_id':'5'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b

@app.route('/6')
def issues6():
    a=coll.find_one({'_id':'6'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b

@app.route('/7')
def issues7():
    a=coll.find_one({'_id':'7'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b

@app.route('/8')
def issues8():
    a=coll.find_one({'_id':'8'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b

@app.route('/9')
def issues9():
    a=coll.find_one({'_id':'9'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b

@app.route('/10')
def issues10():
    a=coll.find_one({'_id':'10'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b

@app.route('/11')
def issues11():
    a=coll.find_one({'_id':'11'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b

@app.route('/12')
def issues12():
    a=coll.find_one({'_id':'12'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b

@app.route('/13')
def issues13():
    a=coll.find_one({'_id':'13'})
    aux=['_id','issues_id', 'url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'node_id', 'number', 'title', 'user' , 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason','draft','pull_request', 'body', 'reactions','timeline_url', 'performed_via_github_app', 'state_reason'] 
    b='<table class="issues">format <tr> <td>'+ str(aux[0]) +'</td> <td>'+ str(aux[1]) +'</td> <td>'+ str(aux[2]) +'</td> <td>'+ str(aux[3]) +'</td> <td>'+ str(aux[4]) +'</td> <td>'+ str(aux[5]) +'</td> <td>'+ str(aux[6]) +'</td> <td>'+ str(aux[7]) +'</td> <td>'+ str(aux[8]) +'</td> <td>'+ str(aux[9]) +'</td> <td>'+ str(aux[10]) +'</td> <td>'+ str(aux[11]) +'</td> <td>'+ str(aux[12]) +'</td> <td>'+ str(aux[13]) +'</td> <td>'+ str(aux[14]) +'</td> <td>'+ str(aux[15]) +'</td> <td>'+ str(aux[16]) +'</td> <td>'+ str(aux[17]) +'</td> <td>'+ str(aux[18]) +'</td> <td>'+ str(aux[19]) +'</td> <td>'+ str(aux[20]) +'</td> <td>'+ str(aux[21]) +'</td> <td>'+ str(aux[22]) +'</td> <td>'+ str(aux[23]) +'</td> <td>'+ str(aux[24]) +'</td> <td>'+ str(aux[26]) +'</td> <td>'+ str(aux[27]) +'</td> <td>'+ str(aux[28]) +'</td> <td>'+ str(aux[29]) +'</td> </tr> <tr> <td>'+ str(a[aux[0]]) +'</td> <td>'+ str(a[aux[1]]) +'</td> <td>'+ str(a[aux[2]]) +'</td> <td>'+ str(a[aux[3]]) +'</td> <td>'+ str(a[aux[4]]) +'</td> <td>'+ str(a[aux[5]]) +'</td> <td>'+ str(a[aux[6]]) +'</td> <td>'+ str(a[aux[7]]) +'</td> <td>'+ str(a[aux[8]]) +'</td> <td>'+ str(a[aux[9]]) +'</td> <td>'+ str(a[aux[10]]) +'</td> <td>'+ str(a[aux[11]]) +'</td> <td>'+ str(a[aux[12]]) +'</td> <td>'+ str(a[aux[13]]) +'</td> <td>'+ str(a[aux[14]]) +'</td> <td>'+ str(a[aux[15]]) +'</td> <td>'+ str(a[aux[16]]) +'</td> <td>'+ str(a[aux[17]]) +'</td> <td>'+ str(a[aux[18]]) +'</td> <td>'+ str(a[aux[19]]) +'</td> <td>'+ str(a[aux[20]]) +'</td> <td>'+ str(a[aux[21]]) +'</td> <td>'+ str(a[aux[22]]) +'</td> <td>'+ str(a[aux[23]]) +'</td> <td>'+ str(a[aux[24]]) +'</td> <td>'+ str(a[aux[26]]) +'</td> <td>'+ str(a[aux[27]]) +'</td> <td>'+ str(a[aux[28]]) +'</td> <td>'+ str(a[aux[29]]) +'</td> </tr> </table>'
    return b


