version: '1'
services:
  app:
    build: ./app
    container_name: breakbad_app
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
  script:
    build: ./app
    container_name: breakbad_script
    links:
      - db
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    command: ["python","./populate.py"]
  db:
    image: mysql:5.7
    container_name: breakbad_db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: breakbad_myadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80