version: "3.8"

services:

       database:
        image: mongo
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: hola
            MONGO_INITDB_ROOT_PASSWORD: hola123


       express:
        image: mongo-express
        container_name: express
        restart: always
        ports: 
            - "8081:8081"
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin123
            ME_CONFIG_MONGODB_SERVER: mongo_DB
            ME_CONFIG_MONGODB_ADMINUSERNAME: hola
            ME_CONFIG_MONGODB_ADMINPASSWORD: hola123
            
            
       pro:
        build: ./eje_1
        container_name: pro
        depends_on:
          - database
        restart: on-failure
        volumes:
          - type: bind
            source: ./eje_1
            target: /usr/src/app


       app:
        build: ./eje_2
        container_name: app
        depends_on:
          - database
        ports: 
            - "5000:5000"
        restart: on-failure
        volumes:
          - type: bind
            source: ./eje_2
            target: /usr/src/app
        




