-- Results of query:
-- select email from USUARIOS
--
BEGIN TRANSACTION;
INSERT INTO  (email) VALUES ('iver.emanuelsen@example.com');
INSERT INTO  (email) VALUES ('ryder.moore@example.com');
INSERT INTO  (email) VALUES ('aster.mangnus@example.com');
INSERT INTO  (email) VALUES ('terrance.freeman@example.com');
INSERT INTO  (email) VALUES ('lena.dunn@example.com');
INSERT INTO  (email) VALUES ('brandy.hart@example.com');
INSERT INTO  (email) VALUES ('rosita.ackermann@example.com');
INSERT INTO  (email) VALUES ('batur.dogan@example.com');
INSERT INTO  (email) VALUES ('albert.daniels@example.com');
INSERT INTO  (email) VALUES ('aubree.gagné@example.com');
INSERT INTO  (email) VALUES ('begüm.akgül@example.com');
INSERT INTO  (email) VALUES ('brooklyn.smith@example.com');
INSERT INTO  (email) VALUES ('eetu.karvonen@example.com');
INSERT INTO  (email) VALUES ('adolfo.benitez@example.com');
INSERT INTO  (email) VALUES ('david.nieto@example.com');
INSERT INTO  (email) VALUES ('gervásia.peixoto@example.com');
INSERT INTO  (email) VALUES ('nelli.karvonen@example.com');
INSERT INTO  (email) VALUES ('alexis.barnaby@example.com');
INSERT INTO  (email) VALUES ('hoi.udo@example.com');
INSERT INTO  (email) VALUES ('nicolas.david@example.com');
INSERT INTO  (email) VALUES ('ruby.taylor@example.com');
INSERT INTO  (email) VALUES ('logan.lavigne@example.com');
INSERT INTO  (email) VALUES ('jack.lam@example.com');
INSERT INTO  (email) VALUES ('oliver.miller@example.com');
INSERT INTO  (email) VALUES ('oskari.koskela@example.com');
INSERT INTO  (email) VALUES ('ariën.vankasteren@example.com');
INSERT INTO  (email) VALUES ('samuel.ranta@example.com');
INSERT INTO  (email) VALUES ('tanya.henderson@example.com');
INSERT INTO  (email) VALUES ('carole.chambers@example.com');
INSERT INTO  (email) VALUES ('alexis.robinson@example.com');
INSERT INTO  (email) VALUES ('?????.???????@example.com');
INSERT INTO  (email) VALUES ('liam.morin@example.com');
INSERT INTO  (email) VALUES ('john.saez@example.com');
INSERT INTO  (email) VALUES ('maëlle.simon@example.com');
INSERT INTO  (email) VALUES ('alexander.madsen@example.com');
INSERT INTO  (email) VALUES ('sonja.mong@example.com');
INSERT INTO  (email) VALUES ('arthur.ross@example.com');
INSERT INTO  (email) VALUES ('emma.larsen@example.com');
INSERT INTO  (email) VALUES ('eugen.gerard@example.com');
INSERT INTO  (email) VALUES ('anisa.caron@example.com');
INSERT INTO  (email) VALUES ('lester.freeman@example.com');
INSERT INTO  (email) VALUES ('albin.stich@example.com');
INSERT INTO  (email) VALUES ('emily.wang@example.com');
INSERT INTO  (email) VALUES ('nalan.dizdar@example.com');
INSERT INTO  (email) VALUES ('hilla.haataja@example.com');
INSERT INTO  (email) VALUES ('arthur.martin@example.com');
INSERT INTO  (email) VALUES ('german.parra@example.com');
INSERT INTO  (email) VALUES ('vildan.daglaroglu@example.com');
INSERT INTO  (email) VALUES ('onur.ertürk@example.com');
INSERT INTO  (email) VALUES ('elliot.mitchell@example.com');
INSERT INTO  (email) VALUES ('elizabeth.vargas@example.com');
INSERT INTO  (email) VALUES ('marte.garvik@example.com');
INSERT INTO  (email) VALUES ('??????.?????@example.com');
INSERT INTO  (email) VALUES ('terry.rose@example.com');
INSERT INTO  (email) VALUES ('lizaine.porto@example.com');
INSERT INTO  (email) VALUES ('louna.simon@example.com');
INSERT INTO  (email) VALUES ('terumi.dacosta@example.com');
INSERT INTO  (email) VALUES ('nesrine.vanwaas@example.com');
INSERT INTO  (email) VALUES ('marshall.carroll@example.com');
INSERT INTO  (email) VALUES ('????????.??????@example.com');
INSERT INTO  (email) VALUES ('verena.giraud@example.com');
INSERT INTO  (email) VALUES ('????.???????@example.com');
INSERT INTO  (email) VALUES ('sam.fletcher@example.com');
INSERT INTO  (email) VALUES ('josef.michel@example.com');
INSERT INTO  (email) VALUES ('theo.jackson@example.com');
INSERT INTO  (email) VALUES ('alison.bradley@example.com');
INSERT INTO  (email) VALUES ('jozef.zeh@example.com');
INSERT INTO  (email) VALUES ('marilyn.watkins@example.com');
INSERT INTO  (email) VALUES ('kelly.lawson@example.com');
INSERT INTO  (email) VALUES ('lilja.murto@example.com');
INSERT INTO  (email) VALUES ('mackenzie.wang@example.com');
INSERT INTO  (email) VALUES ('lesa.horton@example.com');
INSERT INTO  (email) VALUES ('hilla.hanka@example.com');
INSERT INTO  (email) VALUES ('vincent.jackson@example.com');
INSERT INTO  (email) VALUES ('ondina.desouza@example.com');
INSERT INTO  (email) VALUES ('?????.??????????@example.com');
INSERT INTO  (email) VALUES ('curtis.wade@example.com');
INSERT INTO  (email) VALUES ('lotta.waara@example.com');
INSERT INTO  (email) VALUES ('freddy.obispo@example.com');
INSERT INTO  (email) VALUES ('tale.alsaker@example.com');
INSERT INTO  (email) VALUES ('jara.lacroix@example.com');
INSERT INTO  (email) VALUES ('xavier.caldeira@example.com');
INSERT INTO  (email) VALUES ('solano.daconceição@example.com');
INSERT INTO  (email) VALUES ('ozan.diemel@example.com');
INSERT INTO  (email) VALUES ('gina.clark@example.com');
INSERT INTO  (email) VALUES ('eli.banks@example.com');
INSERT INTO  (email) VALUES ('jonathan.poulsen@example.com');
INSERT INTO  (email) VALUES ('belarmino.freitas@example.com');
INSERT INTO  (email) VALUES ('ethan.singh@example.com');
INSERT INTO  (email) VALUES ('filippa.sture@example.com');
INSERT INTO  (email) VALUES ('jonah.bu@example.com');
INSERT INTO  (email) VALUES ('wallace.peterson@example.com');
INSERT INTO  (email) VALUES ('thea.morris@example.com');
INSERT INTO  (email) VALUES ('isaiah.terry@example.com');
INSERT INTO  (email) VALUES ('olivia.madsen@example.com');
INSERT INTO  (email) VALUES ('shannon.diaz@example.com');
INSERT INTO  (email) VALUES ('vidar.joling@example.com');
INSERT INTO  (email) VALUES ('cooper.king@example.com');
INSERT INTO  (email) VALUES ('hans dieter.stork@example.com');
INSERT INTO  (email) VALUES ('sergio.byrd@example.com');
INSERT INTO  (email) VALUES ('german.hidalgo@example.com');
INSERT INTO  (email) VALUES ('william.jørgensen@example.com');
INSERT INTO  (email) VALUES ('???.????????@example.com');
INSERT INTO  (email) VALUES ('sílnior.dacosta@example.com');
INSERT INTO  (email) VALUES ('leonard.rey@example.com');
INSERT INTO  (email) VALUES ('filippa.petersen@example.com');
INSERT INTO  (email) VALUES ('edwin.jacobs@example.com');
INSERT INTO  (email) VALUES ('lourens.passchier@example.com');
INSERT INTO  (email) VALUES ('olivia.thomas@example.com');
INSERT INTO  (email) VALUES ('gary.andrews@example.com');
INSERT INTO  (email) VALUES ('tyler.lewis@example.com');
INSERT INTO  (email) VALUES ('jael.boontjes@example.com');
INSERT INTO  (email) VALUES ('léandro.morin@example.com');
INSERT INTO  (email) VALUES ('lydia.pierre@example.com');
INSERT INTO  (email) VALUES ('mario.lucas@example.com');
INSERT INTO  (email) VALUES ('nelli.neva@example.com');
INSERT INTO  (email) VALUES ('jeppe.larsen@example.com');
INSERT INTO  (email) VALUES ('jenny.campbell@example.com');
INSERT INTO  (email) VALUES ('malak.habberstad@example.com');
INSERT INTO  (email) VALUES ('çetin.sadiklar@example.com');
INSERT INTO  (email) VALUES ('hilla.perko@example.com');
INSERT INTO  (email) VALUES ('ethel.garza@example.com');
INSERT INTO  (email) VALUES ('zoe.margaret@example.com');
INSERT INTO  (email) VALUES ('jacob.olsen@example.com');
INSERT INTO  (email) VALUES ('giovani.fogaça@example.com');
INSERT INTO  (email) VALUES ('juho.halonen@example.com');
INSERT INTO  (email) VALUES ('célestin.dubois@example.com');
INSERT INTO  (email) VALUES ('manuela.nuñez@example.com');
INSERT INTO  (email) VALUES ('oliver.kantola@example.com');
INSERT INTO  (email) VALUES ('????.????????@example.com');


-- Results of query:
-- select count(gender) from USUARIOS where gender = 'female'
--
BEGIN TRANSACTION;
INSERT INTO  ("count(gender)") VALUES (62);



-- Results of query:
-- select * from USUARIOS where gender = 'female'
--
BEGIN TRANSACTION;
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (3, 'female', 'ms', 'aster', 'mangnus', 'aster.mangnus@example.com', '9868 eligenstraat', 'tytsjerksteradiel', 'drenthe', '74618', '39.1090', '36.4100', 'smallrabbit392', 'sassy1');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (5, 'female', 'mrs', 'lena', 'dunn', 'lena.dunn@example.com', '7125 lone wolf trail', 'grants pass', 'new jersey', '75157', '46.0477', '2.4154', 'heavytiger295', '20202020');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (6, 'female', 'ms', 'brandy', 'hart', 'brandy.hart@example.com', '3881 samaritan dr', 'queanbeyan', 'new south wales', '2158', '60.6289', '-99.4662', 'smallwolf600', 'damien');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (7, 'female', 'ms', 'rosita', 'ackermann', 'rosita.ackermann@example.com', 'waldstraße 191', 'mössingen', 'saarland', '91937', '16.6881', '-103.9957', 'ticklishostrich198', 'larkin');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (10, 'female', 'mrs', 'aubree', 'gagné', 'aubree.gagné@example.com', '1252 duke st', 'russell', 'nova scotia', 'X7V 9B6', '-31.1525', '168.8166', 'whitefrog562', 'yvette');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (11, 'female', 'miss', 'begüm', 'akgül', 'begüm.akgül@example.com', '2109 atatürk sk', 'kirklareli', 'usak', '17802', '5.8449', '56.6331', 'sadfrog477', 'brown');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (12, 'female', 'ms', 'brooklyn', 'smith', 'brooklyn.smith@example.com', '145 bay view road', 'whangarei', 'canterbury', '35136', '25.3470', '120.5553', 'happymouse178', 'written');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (16, 'female', 'ms', 'gervásia', 'peixoto', 'gervásia.peixoto@example.com', '1890 rua dezessete ', 'jacareí', 'amapá', '11841', '-11.6103', '-35.8017', 'yellowrabbit412', '1003');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (17, 'female', 'ms', 'nelli', 'karvonen', 'nelli.karvonen@example.com', '5059 tahmelantie', 'pälkäne', 'southern savonia', '75786', '84.6215', '-53.6042', 'redpanda999', 'quasar');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (19, 'female', 'mrs', 'hoi', 'udo', 'hoi.udo@example.com', '9878 agnietenstraat', 'zaltbommel', 'gelderland', '49018', '49.5450', '163.2567', 'whiteelephant520', 'birthday1');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (21, 'female', 'ms', 'ruby', 'taylor', 'ruby.taylor@example.com', '4724 the square', 'wellington', 'gisborne', '56677', '-74.8978', '-17.2756', 'bluemouse464', 'gideon');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (28, 'female', 'mrs', 'tanya', 'henderson', 'tanya.henderson@example.com', '9656 hillcrest rd', 'santa maria', 'oklahoma', '28300', '-71.5664', '103.8411', 'greenpeacock191', 'fowler');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (29, 'female', 'ms', 'carole', 'chambers', 'carole.chambers@example.com', '6152 preston rd', 'red oak', 'north dakota', '34166', '39.9776', '68.1150', 'redostrich808', 'doctor');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (30, 'female', 'miss', 'alexis', 'robinson', 'alexis.robinson@example.com', '3949 nelson quay', 'greymouth', 'nelson', '47789', '53.6957', '164.5805', 'greenmouse636', 'rochelle');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (31, 'female', 'miss', '?????', '???????', '?????.???????@example.com', '4332 ???? ???? ?????', '????', '?????? ?????', '38577', '-3.4134', '51.3525', 'crazylion358', 'guess');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (34, 'female', 'ms', 'maëlle', 'simon', 'maëlle.simon@example.com', '3906 rue docteur-bonhomme', 'roubaix', 'ardèche', '71907', '-73.2231', '-14.1475', 'bluepeacock742', 'blacklab');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (36, 'female', 'ms', 'sonja', 'mong', 'sonja.mong@example.com', 'festningsplassen 9053', 'ferkingstad', 'sør-trøndelag', '2673', '-76.8876', '175.6136', 'heavyfrog493', 'heat');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (38, 'female', 'mrs', 'emma', 'larsen', 'emma.larsen@example.com', '2847 blåbærvej', 'aalborg s.ø.', 'nordjylland', '69965', '-85.1805', '-57.9413', 'smallgoose253', 'bridge');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (40, 'female', 'mademoiselle', 'anisa', 'caron', 'anisa.caron@example.com', '8644 rue de labbé-migne', 'écublens (fr)', 'bern', '7841', '4.6509', '126.2928', 'orangekoala204', 'sommer');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (43, 'female', 'mrs', 'emily', 'wang', 'emily.wang@example.com', '3140 pine hill road', 'hamilton', 'northland', '16200', '-76.5339', '41.1662', 'greenbutterfly417', 'magic');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (44, 'female', 'miss', 'nalan', 'dizdar', 'nalan.dizdar@example.com', '2358 mevlana cd', 'isparta', 'kastamonu', '83171', '23.5484', '-31.5145', 'heavygoose242', 'lumber');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (45, 'female', 'miss', 'hilla', 'haataja', 'hilla.haataja@example.com', '997 tahmelantie', 'kangasala', 'tavastia proper', '60164', '-74.7394', '-50.8582', 'purplefrog357', 'beastie');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (48, 'female', 'mrs', 'vildan', 'daglaroglu', 'vildan.daglaroglu@example.com', '5035 doktorlar cd', 'artvin', 'mersin', '44426', '-13.6581', '-51.6930', 'bigbutterfly966', 'donnie');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (51, 'female', 'mrs', 'elizabeth', 'vargas', 'elizabeth.vargas@example.com', '427 manchester road', 'armagh', 'lincolnshire', 'C7I 3EX', '17.1686', '-123.9281', 'tinytiger725', 'fuking');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (52, 'female', 'miss', 'marte', 'garvik', 'marte.garvik@example.com', 'ostadalsveien 3867', 'lyngdal', 'nord-trøndelag', '1661', '-39.5589', '-81.0906', 'crazyfrog942', 'byteme');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (53, 'female', 'ms', '??????', '?????', '??????.?????@example.com', '5155 ????? ?????', '???????', '???????? ? ????????', '17675', '35.0129', '29.8533', 'goldenelephant354', 'fang');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (55, 'female', 'ms', 'lizaine', 'porto', 'lizaine.porto@example.com', '8828 rua joão xxiii', 'simões filho', 'goiás', '81632', '55.2533', '42.4683', 'organicfish498', '1213');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (56, 'female', 'mrs', 'louna', 'simon', 'louna.simon@example.com', '1969 montée du chemin-neuf', 'saint-pierre', 'gers', '52166', '83.9311', '-51.4675', 'blackbear512', 'hayabusa');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (57, 'female', 'ms', 'terumi', 'da costa', 'terumi.dacosta@example.com', '8010 rua quatro', 'caxias do sul', 'rio de janeiro', '38660', '-29.1036', '29.6767', 'orangerabbit827', 'brady');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (58, 'female', 'mrs', 'nesrine', 'van waas', 'nesrine.vanwaas@example.com', '9675 korte nieuwstraat', 'den helder', 'friesland', '56930', '62.2443', '143.9951', 'organicswan576', 'encore');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (61, 'female', 'madame', 'verena', 'giraud', 'verena.giraud@example.com', '1210 boulevard de la duchère', 'les genevez (ju)', 'basel-stadt', '5494', '-40.7578', '-168.9906', 'bluedog723', 'justdoit');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (62, 'female', 'mrs', '????', '???????', '????.???????@example.com', '6850 ???????', '??????', '????', '32965', '-11.8394', '-79.7415', 'goldenduck581', 'howard');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (63, 'female', 'mrs', 'sam', 'fletcher', 'sam.fletcher@example.com', '5036 grove road', 'stirling', 'highlands and islands', 'MZ64 2FW', '10.9942', '-128.1512', 'lazyrabbit992', 'stephen1');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (66, 'female', 'miss', 'alison', 'bradley', 'alison.bradley@example.com', '4066 richmond park', 'athlone', 'waterford', '62419', '-48.8043', '-151.4619', 'whitemeercat885', 'triangle');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (68, 'female', 'ms', 'marilyn', 'watkins', 'marilyn.watkins@example.com', '6265 hamilton ave', 'bueblo', 'georgia', '23299', '-24.8556', '173.9899', 'greenwolf473', 'houdini');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (69, 'female', 'ms', 'kelly', 'lawson', 'kelly.lawson@example.com', '2986 station road', 'portarlington', 'louth', '84755', '-88.0056', '36.2661', 'purplecat193', 'bumper');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (70, 'female', 'ms', 'lilja', 'murto', 'lilja.murto@example.com', '7611 nordenskiöldinkatu', 'kitee', 'northern ostrobothnia', '50607', '-61.0808', '-134.8245', 'beautifulgoose228', '12121212');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (71, 'female', 'ms', 'mackenzie', 'wang', 'mackenzie.wang@example.com', '9197 panama road', 'upper hutt', 'southland', '68617', '28.6826', '-117.5390', 'silverzebra372', 'spice');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (72, 'female', 'mrs', 'lesa', 'horton', 'lesa.horton@example.com', '6967 nowlin rd', 'belen', 'kansas', '23873', '-29.5202', '-99.5607', 'beautifulpeacock949', 'swords');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (73, 'female', 'mrs', 'hilla', 'hanka', 'hilla.hanka@example.com', '6285 myllypuronkatu', 'kangasala', 'tavastia proper', '96710', '11.1122', '-65.1544', 'whiteleopard464', 'digital');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (75, 'female', 'mrs', 'ondina', 'de souza', 'ondina.desouza@example.com', '4357 rua santa maria ', 'suzano', 'minas gerais', '41840', '70.4331', '-80.5362', 'brownleopard552', 'farm');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (76, 'female', 'ms', '?????', '?????? ????', '?????.??????????@example.com', '7730 ?????? / ????', '?????', '?????', '22691', '-16.6633', '-86.6178', 'sadgoose814', 'amazon');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (78, 'female', 'ms', 'lotta', 'waara', 'lotta.waara@example.com', '8732 rautatienkatu', 'leppävirta', 'finland proper', '83929', '-18.9061', '2.0310', 'bigelephant365', 'dipper');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (80, 'female', 'mrs', 'tale', 'alsaker', 'tale.alsaker@example.com', 'munkerudåsen 3870', 'sandeid', 'nord-trøndelag', '4307', '43.9513', '-157.3212', 'silverpeacock705', 'blonds');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (81, 'female', 'madame', 'jara', 'lacroix', 'jara.lacroix@example.com', '2235 rue de cuire', 'genthod', 'basel-stadt', '4739', '88.0059', '113.6139', 'blackbear899', 'close');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (85, 'female', 'ms', 'gina', 'clark', 'gina.clark@example.com', '5197 thornridge cir', 'albany', 'queensland', '8336', '-82.2507', '36.9270', 'tinyduck373', 'volvo');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (90, 'female', 'miss', 'filippa', 'sture', 'filippa.sture@example.com', 'hockeyveien 7228', 'straume', 'rogaland', '4150', '32.5653', '-9.5091', 'tinykoala931', 'helmut');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (93, 'female', 'ms', 'thea', 'morris', 'thea.morris@example.com', '8844 lake terrace', 'hamilton', 'canterbury', '53300', '39.3814', '-33.9691', 'whiteelephant770', 'jack1');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (95, 'female', 'ms', 'olivia', 'madsen', 'olivia.madsen@example.com', '1379 dyssevænget', 'juelsminde', 'nordjylland', '40293', '63.8454', '-47.4885', 'goldenleopard297', 'roxy');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (96, 'female', 'ms', 'shannon', 'diaz', 'shannon.diaz@example.com', '4449 hogan st', 'traralgon', 'western australia', '1287', '10.1659', '-62.8819', 'bigduck883', 'kendra');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (104, 'female', 'ms', 'sílnior', 'da costa', 'sílnior.dacosta@example.com', '5533 rua das flores ', 'gravataí', 'sergipe', '87610', '-36.4838', '171.7230', 'brownleopard630', 'comanche');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (106, 'female', 'mrs', 'filippa', 'petersen', 'filippa.petersen@example.com', '3327 kildegårdsvej', 'nørre sundby', 'nordjylland', '34107', '82.6755', '40.8087', 'whitepeacock447', 'allan');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (109, 'female', 'ms', 'olivia', 'thomas', 'olivia.thomas@example.com', '9742 anzac drive', 'whangarei', 'taranaki', '45512', '24.1497', '-12.4545', 'blackbird693', 'claire');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (112, 'female', 'mrs', 'jael', 'boontjes', 'jael.boontjes@example.com', '2716 plompetorengracht', 'hollands kroon', 'zeeland', '13313', '-79.4044', '33.4939', 'bigpeacock727', 'marcello');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (114, 'female', 'madame', 'lydia', 'pierre', 'lydia.pierre@example.com', '8937 rue de gerland', 'chur', 'appenzell innerrhoden', '4629', '82.0510', '25.7585', 'blackbird910', 'kiss');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (116, 'female', 'mrs', 'nelli', 'neva', 'nelli.neva@example.com', '1380 esplanadi', 'merijärvi', 'finland proper', '24090', '-72.6702', '-74.7321', 'blackpanda227', 'budapest');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (118, 'female', 'miss', 'jenny', 'campbell', 'jenny.campbell@example.com', '9709 park avenue', 'cashel', 'clare', '34811', '65.3715', '-165.0005', 'ticklishpeacock105', 'louie');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (119, 'female', 'miss', 'malak', 'habberstad', 'malak.habberstad@example.com', 'skullerudstubben 6679', 'kjellmyra', 'rogaland', '6727', '4.5707', '-122.6303', 'happygorilla511', 'glotest');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (121, 'female', 'mrs', 'hilla', 'perko', 'hilla.perko@example.com', '6789 pyynikintie', 'virrat', 'kainuu', '44544', '69.3051', '-110.2416', 'goldengorilla466', 'gramma');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (122, 'female', 'ms', 'ethel', 'garza', 'ethel.garza@example.com', '519 hickory creek dr', 'pueblo', 'california', '21848', '27.0341', '159.3944', 'smallgoose956', 'jojo');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (123, 'female', 'mrs', 'zoe', 'margaret', 'zoe.margaret@example.com', '2342 park rd', 'hampstead', 'ontario', 'B3Z 8O8', '37.2958', '86.9845', 'goldenrabbit156', 'snuffy');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (128, 'female', 'ms', 'manuela', 'nuñez', 'manuela.nuñez@example.com', '7116 calle del pez', 'alcobendas', 'andalucía', '83084', '9.2773', '-152.2577', 'redgorilla551', 'bigone');



-- Results of query:
-- select count(gender) from USUARIOS where gender = 'male'
--
BEGIN TRANSACTION;
INSERT INTO  ("count(gender)") VALUES (68);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;



-- Results of query:
-- select * from USUARIOS where gender = 'male'
--
BEGIN TRANSACTION;
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (1, 'male', 'mr', 'iver', 'emanuelsen', 'iver.emanuelsen@example.com', 'daniel walstads vei 534', 'råkvågen', 'akershus', '3244', '49.2262', '-22.8802', 'tinylion945', 'seagull');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (2, 'male', 'mr', 'ryder', 'moore', 'ryder.moore@example.com', '4595 marshland road', 'napier', 'northland', '70891', '-48.8582', '74.4573', 'greendog952', 'duffman');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (4, 'male', 'mr', 'terrance', 'freeman', 'terrance.freeman@example.com', '7348 queens road', 'swansea', 'hampshire', 'OG5S 3UU', '39.2361', '-152.1850', 'orangeswan512', '626262');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (8, 'male', 'mr', 'batur', 'dogan', 'batur.dogan@example.com', '7587 anafartalar cd', 'ankara', 'Izmir', '46049', '-16.9461', '18.0035', 'purplekoala144', 'columbia');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (9, 'male', 'mr', 'albert', 'daniels', 'albert.daniels@example.com', '3848 the crescent', 'wolverhampton', 'county londonderry', 'VP0L 4TA', '64.6048', '44.7529', 'heavycat646', 'players');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (13, 'male', 'mr', 'eetu', 'karvonen', 'eetu.karvonen@example.com', '865 fredrikinkatu', 'taipalsaari', 'pirkanmaa', '53672', '38.0410', '-131.8209', 'blackwolf385', 'eugene');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (14, 'male', 'mr', 'adolfo', 'benitez', 'adolfo.benitez@example.com', '1833 calle de la luna', 'la palma', 'andalucía', '72385', '32.8588', '94.8045', 'brownswan946', 'milo');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (15, 'male', 'mr', 'david', 'nieto', 'david.nieto@example.com', '2538 calle mota', 'valladolid', 'extremadura', '45440', '63.0960', '68.5664', 'orangecat300', '23232323');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (18, 'male', 'mr', 'alexis', 'barnaby', 'alexis.barnaby@example.com', '4889 vimy st', 'georgetown', 'new brunswick', 'D2N 2I3', '67.9508', '92.9627', 'ticklishbird470', 'caroline');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (20, 'male', 'mr', 'nicolas', 'david', 'nicolas.david@example.com', '1315 rue denfert-rochereau', 'orléans', 'seine-maritime', '61202', '71.2420', '-24.4787', 'brownwolf817', 'express');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (22, 'male', 'mr', 'logan', 'lavigne', 'logan.lavigne@example.com', '1830 concession road 23', 'georgetown', 'new brunswick', 'I1H 7D0', '69.2977', '-33.6124', 'blueladybug803', 'tickle');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (23, 'male', 'mr', 'jack', 'lam', 'jack.lam@example.com', '2384 george st', 'odessa', 'ontario', 'Z4R 0R2', '-10.5123', '-23.1153', 'browngorilla904', 'titan');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (24, 'male', 'mr', 'oliver', 'miller', 'oliver.miller@example.com', '1873 west ave', 'havelock', 'nova scotia', 'W2A 0J6', '-55.9124', '140.8537', 'sadmeercat435', 'spanker');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (25, 'male', 'mr', 'oskari', 'koskela', 'oskari.koskela@example.com', '1365 korkeavuorenkatu', 'orivesi', 'southern ostrobothnia', '98585', '69.5345', '-116.7377', 'ticklishladybug773', '1112');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (26, 'male', 'mr', 'ariën', 'van kasteren', 'ariën.vankasteren@example.com', '2320 janskerkhof', 'dalfsen', 'friesland', '41591', '30.7169', '-174.7947', 'brownbutterfly760', 'little1');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (27, 'male', 'mr', 'samuel', 'ranta', 'samuel.ranta@example.com', '748 hämeentie', 'oulunsalo', 'uusimaa', '22028', '-83.1921', '-14.4413', 'goldenelephant474', 'checker');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (32, 'male', 'mr', 'liam', 'morin', 'liam.morin@example.com', '8217 rue duguesclin', 'besançon', 'dordogne', '51131', '15.8641', '-42.5728', 'silverzebra421', 'marsh');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (33, 'male', 'mr', 'john', 'saez', 'john.saez@example.com', '414 avenida de andalucía', 'santa cruz de tenerife', 'ceuta', '72443', '79.9958', '66.9364', 'orangebear132', 'starr');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (35, 'male', 'mr', 'alexander', 'madsen', 'alexander.madsen@example.com', '3786 valmuemarken', 'juelsminde', 'syddanmark', '66675', '-72.0714', '-13.0248', 'angrygoose578', 'suckers');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (37, 'male', 'mr', 'arthur', 'ross', 'arthur.ross@example.com', '2615 victoria road', 'newcastle upon tyne', 'surrey', 'Z6 0TL', '-9.8925', '-139.2526', 'lazywolf653', 'howdy');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (39, 'male', 'monsieur', 'eugen', 'gerard', 'eugen.gerard@example.com', '738 place du 22 novembre 1943', 'payerne', 'thurgau', '7906', '-33.5773', '-8.8663', 'beautifulpanda154', 'deadpool');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (41, 'male', 'mr', 'lester', 'freeman', 'lester.freeman@example.com', '2855 adams st', 'corpus christi', 'mississippi', '82664', '72.2862', '-103.6993', 'yellowpeacock851', 'brianna');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (42, 'male', 'mr', 'albin', 'stich', 'albin.stich@example.com', 'schulweg 49', 'pegnitz', 'bremen', '18573', '-60.5865', '-79.6750', 'happyelephant964', 'song');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (46, 'male', 'mr', 'arthur', 'martin', 'arthur.martin@example.com', '8156 north street', 'gisborne', 'otago', '71536', '39.0068', '62.5856', 'sadrabbit423', '1818');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (47, 'male', 'mr', 'german', 'parra', 'german.parra@example.com', '4142 calle de arturo soria', 'pontevedra', 'aragón', '64937', '-72.5203', '84.0807', 'happyfish221', 'colombia');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (49, 'male', 'mr', 'onur', 'ertürk', 'onur.ertürk@example.com', '8642 atatürk sk', 'sinop', 'hatay', '55136', '3.0736', '-2.5911', 'greenelephant376', '4545');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (50, 'male', 'mr', 'elliot', 'mitchell', 'elliot.mitchell@example.com', '5488 alfred st', 'keswick', 'alberta', 'D6G 0T2', '22.1534', '-160.4332', 'brownladybug765', 'titans');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (54, 'male', 'mr', 'terry', 'rose', 'terry.rose@example.com', '6330 dogwood ave', 'hobart', 'australian capital territory', '9386', '75.1010', '63.2793', 'orangefrog125', 'nt5d27');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (59, 'male', 'mr', 'marshall', 'carroll', 'marshall.carroll@example.com', '2317 hickory creek dr', 'greeley', 'georgia', '38598', '5.5711', '-68.6735', 'redgorilla840', 'prozac');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (60, 'male', 'mr', '????????', '??? ???', '????????.??????@example.com', '9593 ????? ?????', '???', '??????', '36745', '17.3164', '-11.7636', 'tinypanda493', 'snowboard');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (64, 'male', 'monsieur', 'josef', 'michel', 'josef.michel@example.com', '9862 rue de labbé-carton', 'surses', 'appenzell innerrhoden', '5380', '31.7129', '64.5675', 'greenfrog700', 'cancun');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (65, 'male', 'mr', 'theo', 'jackson', 'theo.jackson@example.com', '9412 saint aubyn street', 'upper hutt', 'auckland', '21028', '-76.1716', '129.6445', 'goldenrabbit602', 'goldfing');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (67, 'male', 'mr', 'jozef', 'zeh', 'jozef.zeh@example.com', 'blumenstraße 58', 'kamenz', 'brandenburg', '65518', '24.0315', '143.6410', 'smallgoose626', 'guan');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (74, 'male', 'mr', 'vincent', 'jackson', 'vincent.jackson@example.com', '7232 tamaki drive', 'whanganui', 'marlborough', '55395', '-52.2305', '-11.6215', 'angrygorilla379', 'dennis');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (77, 'male', 'mr', 'curtis', 'wade', 'curtis.wade@example.com', '8392 new road', 'loughrea', 'cork city', '53237', '-37.5364', '1.8523', 'brownelephant112', 'hun999');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (79, 'male', 'mr', 'freddy', 'obispo', 'freddy.obispo@example.com', '4944 vleutenseweg', 'huizen', 'limburg', '54957', '-41.8134', '124.4098', 'organicmeercat531', 'asasas');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (82, 'male', 'mr', 'xavier', 'caldeira', 'xavier.caldeira@example.com', '2098 rua primeiro de maio ', 'vila velha', 'distrito federal', '28119', '-44.8539', '-9.4039', 'crazymouse928', 'excite');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (83, 'male', 'mr', 'solano', 'da conceição', 'solano.daconceição@example.com', '9492 rua principal', 'vila velha', 'são paulo', '34433', '-11.2812', '-18.6154', 'goldentiger184', 'zhao');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (84, 'male', 'mr', 'ozan', 'diemel', 'ozan.diemel@example.com', '8534 prins hendriklaan', 'stichtse vecht', 'drenthe', '24848', '-73.2672', '-35.9985', 'yellowdog249', 'overkill');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (86, 'male', 'mr', 'eli', 'banks', 'eli.banks@example.com', '1106 ranchview dr', 'bunbury', 'new south wales', '8422', '-16.7845', '-59.8524', 'happylion843', 'deep');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (87, 'male', 'mr', 'jonathan', 'poulsen', 'jonathan.poulsen@example.com', '4387 fjordvej', 'ishoej', 'hovedstaden', '59516', '30.8980', '22.9770', 'whitemouse684', 'passmast');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (88, 'male', 'mr', 'belarmino', 'freitas', 'belarmino.freitas@example.com', '7261 rua sete de setembro ', 'maracanaú', 'amapá', '71037', '46.2800', '-77.3199', 'lazymouse345', 'beowulf');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (89, 'male', 'mr', 'ethan', 'singh', 'ethan.singh@example.com', '1009 frederick ave', 'inwood', 'northwest territories', 'G0O 9P7', '83.7346', '168.5300', 'greenzebra353', 'rock');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (91, 'male', 'mr', 'jonah', 'bu', 'jonah.bu@example.com', 'hanåveien 183', 'monssveen', 'møre og romsdal', '6201', '-15.3116', '9.4923', 'greenbutterfly269', 'viper');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (92, 'male', 'mr', 'wallace', 'peterson', 'wallace.peterson@example.com', '5529 w dallas st', 'tamworth', 'new south wales', '7234', '43.0836', '-48.5495', 'orangeladybug863', 'pics');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (94, 'male', 'mr', 'isaiah', 'terry', 'isaiah.terry@example.com', '5308 westmoreland street', 'nenagh', 'sligo', '21183', '-83.3423', '-133.3610', 'greenduck443', 'deep');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (97, 'male', 'mr', 'vidar', 'joling', 'vidar.joling@example.com', '3083 mariaplaats', 'oisterwijk', 'friesland', '27458', '31.7544', '-86.9453', 'beautifulfrog300', 'clint');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (98, 'male', 'mr', 'cooper', 'king', 'cooper.king@example.com', '6208 dickens street', 'hamilton', 'northland', '94964', '-13.1664', '-3.8817', 'lazybird830', 'megan1');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (99, 'male', 'mr', 'hans dieter', 'stork', 'hans dieter.stork@example.com', 'berliner straße 148', 'penkun', 'brandenburg', '25128', '-2.4926', '-139.9371', 'tinybear396', 'precious');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (100, 'male', 'mr', 'sergio', 'byrd', 'sergio.byrd@example.com', '2374 cork street', 'mallow', 'laois', '67825', '-33.8122', '-13.3452', 'lazygorilla377', 'lakewood');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (101, 'male', 'mr', 'german', 'hidalgo', 'german.hidalgo@example.com', '3228 calle del barquillo', 'vigo', 'navarra', '89718', '-17.7214', '-118.7040', 'goldenwolf905', 'knock');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (102, 'male', 'mr', 'william', 'jørgensen', 'william.jørgensen@example.com', '2963 dalsvinget', 'odense sv', 'danmark', '50184', '54.8126', '54.8465', 'crazyswan524', 'spot');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (103, 'male', 'mr', '???', '????? ???', '???.????????@example.com', '2944 ????? ?????', '??????', '?????', '94662', '-87.2234', '-70.6676', 'bigfish243', 'ethan');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (105, 'male', 'monsieur', 'leonard', 'rey', 'leonard.rey@example.com', '9400 rue de labbé-grégoire', 'coeuve', 'uri', '6438', '-31.4006', '-125.8872', 'reddog126', 'cang');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (107, 'male', 'mr', 'edwin', 'jacobs', 'edwin.jacobs@example.com', '4511 camden ave', 'rockhampton', 'queensland', '8082', '-83.8499', '-28.7188', 'redgoose676', 'granny');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (108, 'male', 'mr', 'lourens', 'passchier', 'lourens.passchier@example.com', '2815 wed', 'bergen', 'noord-brabant', '11815', '-0.1146', '-92.3709', 'blackgorilla897', '1022');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (110, 'male', 'mr', 'gary', 'andrews', 'gary.andrews@example.com', '2089 west street', 'liverpool', 'fife', 'G2L 8PH', '-89.1120', '23.3307', 'heavydog602', 'front242');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (111, 'male', 'mr', 'tyler', 'lewis', 'tyler.lewis@example.com', '9738 maraekakaho road', 'blenheim', 'canterbury', '65589', '-23.0799', '-164.0636', 'yellowcat957', 'brad');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (113, 'male', 'mr', 'léandro', 'morin', 'léandro.morin@example.com', '4771 rue pasteur', 'rueil-malmaison', 'meurthe-et-moselle', '75649', '-89.5892', '-29.9362', 'bigmouse244', 'magic1');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (115, 'male', 'mr', 'mario', 'lucas', 'mario.lucas@example.com', '9989 oaks cross', 'swansea', 'avon', 'PZ8Y 4QR', '-35.4735', '5.0076', 'bigfish701', 'woohoo');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (117, 'male', 'mr', 'jeppe', 'larsen', 'jeppe.larsen@example.com', '3489 lundevej', 'ansager', 'midtjylland', '35630', '36.7492', '-171.2212', 'tinybear801', 'never');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (120, 'male', 'mr', 'çetin', 'sadiklar', 'çetin.sadiklar@example.com', '1385 necatibey cd', 'batman', 'bursa', '12099', '-14.7139', '74.9559', 'sadmouse513', 'terror');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (124, 'male', 'mr', 'jacob', 'olsen', 'jacob.olsen@example.com', '2657 lyøvej', 'askeby', 'sjælland', '44777', '-28.0223', '-179.3550', 'angryostrich735', 'better');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (125, 'male', 'mr', 'giovani', 'fogaça', 'giovani.fogaça@example.com', '9726 rua da paz ', 'gravataí', 'rio grande do norte', '57215', '-19.0561', '-35.8971', 'bigmeercat494', 'foxylady');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (126, 'male', 'mr', 'juho', 'halonen', 'juho.halonen@example.com', '2395 siilitie', 'virolahti', 'south karelia', '24329', '-74.1720', '-56.6602', 'blackrabbit851', 'brodie');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (127, 'male', 'mr', 'célestin', 'dubois', 'célestin.dubois@example.com', '2153 place de labbé-basset', 'saint-pierre', 'pyrénées-atlantiques', '10569', '45.6019', '176.8785', 'greentiger839', 'clevelan');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (129, 'male', 'mr', 'oliver', 'kantola', 'oliver.kantola@example.com', '1726 siilitie', 'luvia', 'päijät-häme', '32974', '-2.8988', '134.1751', 'lazycat195', 'mannn');
INSERT INTO  (id, gender, title, first_name, last_name, email, street, city, state, postcode, latitude, longitude, username, password) VALUES (130, 'male', 'mr', '????', '????? ???', '????.????????@example.com', '6070 ??????', '??????', '?????', '56553', '-1.8828', '-74.2035', 'goldenelephant730', 'kotaku');



-- Results of query:
-- select first_name, last_name, email, street, city, state, postcode from USUARIOS
--
BEGIN TRANSACTION;
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('iver', 'emanuelsen', 'iver.emanuelsen@example.com', 'daniel walstads vei 534', 'råkvågen', 'akershus', '3244');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('ryder', 'moore', 'ryder.moore@example.com', '4595 marshland road', 'napier', 'northland', '70891');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('aster', 'mangnus', 'aster.mangnus@example.com', '9868 eligenstraat', 'tytsjerksteradiel', 'drenthe', '74618');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('terrance', 'freeman', 'terrance.freeman@example.com', '7348 queens road', 'swansea', 'hampshire', 'OG5S 3UU');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('lena', 'dunn', 'lena.dunn@example.com', '7125 lone wolf trail', 'grants pass', 'new jersey', '75157');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('brandy', 'hart', 'brandy.hart@example.com', '3881 samaritan dr', 'queanbeyan', 'new south wales', '2158');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('rosita', 'ackermann', 'rosita.ackermann@example.com', 'waldstraße 191', 'mössingen', 'saarland', '91937');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('batur', 'dogan', 'batur.dogan@example.com', '7587 anafartalar cd', 'ankara', 'Izmir', '46049');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('albert', 'daniels', 'albert.daniels@example.com', '3848 the crescent', 'wolverhampton', 'county londonderry', 'VP0L 4TA');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('aubree', 'gagné', 'aubree.gagné@example.com', '1252 duke st', 'russell', 'nova scotia', 'X7V 9B6');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('begüm', 'akgül', 'begüm.akgül@example.com', '2109 atatürk sk', 'kirklareli', 'usak', '17802');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('brooklyn', 'smith', 'brooklyn.smith@example.com', '145 bay view road', 'whangarei', 'canterbury', '35136');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('eetu', 'karvonen', 'eetu.karvonen@example.com', '865 fredrikinkatu', 'taipalsaari', 'pirkanmaa', '53672');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('adolfo', 'benitez', 'adolfo.benitez@example.com', '1833 calle de la luna', 'la palma', 'andalucía', '72385');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('david', 'nieto', 'david.nieto@example.com', '2538 calle mota', 'valladolid', 'extremadura', '45440');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('gervásia', 'peixoto', 'gervásia.peixoto@example.com', '1890 rua dezessete ', 'jacareí', 'amapá', '11841');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('nelli', 'karvonen', 'nelli.karvonen@example.com', '5059 tahmelantie', 'pälkäne', 'southern savonia', '75786');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('alexis', 'barnaby', 'alexis.barnaby@example.com', '4889 vimy st', 'georgetown', 'new brunswick', 'D2N 2I3');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('hoi', 'udo', 'hoi.udo@example.com', '9878 agnietenstraat', 'zaltbommel', 'gelderland', '49018');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('nicolas', 'david', 'nicolas.david@example.com', '1315 rue denfert-rochereau', 'orléans', 'seine-maritime', '61202');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('ruby', 'taylor', 'ruby.taylor@example.com', '4724 the square', 'wellington', 'gisborne', '56677');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('logan', 'lavigne', 'logan.lavigne@example.com', '1830 concession road 23', 'georgetown', 'new brunswick', 'I1H 7D0');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('jack', 'lam', 'jack.lam@example.com', '2384 george st', 'odessa', 'ontario', 'Z4R 0R2');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('oliver', 'miller', 'oliver.miller@example.com', '1873 west ave', 'havelock', 'nova scotia', 'W2A 0J6');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('oskari', 'koskela', 'oskari.koskela@example.com', '1365 korkeavuorenkatu', 'orivesi', 'southern ostrobothnia', '98585');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('ariën', 'van kasteren', 'ariën.vankasteren@example.com', '2320 janskerkhof', 'dalfsen', 'friesland', '41591');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('samuel', 'ranta', 'samuel.ranta@example.com', '748 hämeentie', 'oulunsalo', 'uusimaa', '22028');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('tanya', 'henderson', 'tanya.henderson@example.com', '9656 hillcrest rd', 'santa maria', 'oklahoma', '28300');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('carole', 'chambers', 'carole.chambers@example.com', '6152 preston rd', 'red oak', 'north dakota', '34166');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('alexis', 'robinson', 'alexis.robinson@example.com', '3949 nelson quay', 'greymouth', 'nelson', '47789');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('?????', '???????', '?????.???????@example.com', '4332 ???? ???? ?????', '????', '?????? ?????', '38577');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('liam', 'morin', 'liam.morin@example.com', '8217 rue duguesclin', 'besançon', 'dordogne', '51131');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('john', 'saez', 'john.saez@example.com', '414 avenida de andalucía', 'santa cruz de tenerife', 'ceuta', '72443');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('maëlle', 'simon', 'maëlle.simon@example.com', '3906 rue docteur-bonhomme', 'roubaix', 'ardèche', '71907');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('alexander', 'madsen', 'alexander.madsen@example.com', '3786 valmuemarken', 'juelsminde', 'syddanmark', '66675');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('sonja', 'mong', 'sonja.mong@example.com', 'festningsplassen 9053', 'ferkingstad', 'sør-trøndelag', '2673');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('arthur', 'ross', 'arthur.ross@example.com', '2615 victoria road', 'newcastle upon tyne', 'surrey', 'Z6 0TL');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('emma', 'larsen', 'emma.larsen@example.com', '2847 blåbærvej', 'aalborg s.ø.', 'nordjylland', '69965');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('eugen', 'gerard', 'eugen.gerard@example.com', '738 place du 22 novembre 1943', 'payerne', 'thurgau', '7906');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('anisa', 'caron', 'anisa.caron@example.com', '8644 rue de labbé-migne', 'écublens (fr)', 'bern', '7841');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('lester', 'freeman', 'lester.freeman@example.com', '2855 adams st', 'corpus christi', 'mississippi', '82664');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('albin', 'stich', 'albin.stich@example.com', 'schulweg 49', 'pegnitz', 'bremen', '18573');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('emily', 'wang', 'emily.wang@example.com', '3140 pine hill road', 'hamilton', 'northland', '16200');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('nalan', 'dizdar', 'nalan.dizdar@example.com', '2358 mevlana cd', 'isparta', 'kastamonu', '83171');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('hilla', 'haataja', 'hilla.haataja@example.com', '997 tahmelantie', 'kangasala', 'tavastia proper', '60164');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('arthur', 'martin', 'arthur.martin@example.com', '8156 north street', 'gisborne', 'otago', '71536');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('german', 'parra', 'german.parra@example.com', '4142 calle de arturo soria', 'pontevedra', 'aragón', '64937');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('vildan', 'daglaroglu', 'vildan.daglaroglu@example.com', '5035 doktorlar cd', 'artvin', 'mersin', '44426');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('onur', 'ertürk', 'onur.ertürk@example.com', '8642 atatürk sk', 'sinop', 'hatay', '55136');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('elliot', 'mitchell', 'elliot.mitchell@example.com', '5488 alfred st', 'keswick', 'alberta', 'D6G 0T2');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('elizabeth', 'vargas', 'elizabeth.vargas@example.com', '427 manchester road', 'armagh', 'lincolnshire', 'C7I 3EX');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('marte', 'garvik', 'marte.garvik@example.com', 'ostadalsveien 3867', 'lyngdal', 'nord-trøndelag', '1661');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('??????', '?????', '??????.?????@example.com', '5155 ????? ?????', '???????', '???????? ? ????????', '17675');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('terry', 'rose', 'terry.rose@example.com', '6330 dogwood ave', 'hobart', 'australian capital territory', '9386');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('lizaine', 'porto', 'lizaine.porto@example.com', '8828 rua joão xxiii', 'simões filho', 'goiás', '81632');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('louna', 'simon', 'louna.simon@example.com', '1969 montée du chemin-neuf', 'saint-pierre', 'gers', '52166');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('terumi', 'da costa', 'terumi.dacosta@example.com', '8010 rua quatro', 'caxias do sul', 'rio de janeiro', '38660');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('nesrine', 'van waas', 'nesrine.vanwaas@example.com', '9675 korte nieuwstraat', 'den helder', 'friesland', '56930');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('marshall', 'carroll', 'marshall.carroll@example.com', '2317 hickory creek dr', 'greeley', 'georgia', '38598');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('????????', '??? ???', '????????.??????@example.com', '9593 ????? ?????', '???', '??????', '36745');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('verena', 'giraud', 'verena.giraud@example.com', '1210 boulevard de la duchère', 'les genevez (ju)', 'basel-stadt', '5494');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('????', '???????', '????.???????@example.com', '6850 ???????', '??????', '????', '32965');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('sam', 'fletcher', 'sam.fletcher@example.com', '5036 grove road', 'stirling', 'highlands and islands', 'MZ64 2FW');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('josef', 'michel', 'josef.michel@example.com', '9862 rue de labbé-carton', 'surses', 'appenzell innerrhoden', '5380');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('theo', 'jackson', 'theo.jackson@example.com', '9412 saint aubyn street', 'upper hutt', 'auckland', '21028');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('alison', 'bradley', 'alison.bradley@example.com', '4066 richmond park', 'athlone', 'waterford', '62419');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('jozef', 'zeh', 'jozef.zeh@example.com', 'blumenstraße 58', 'kamenz', 'brandenburg', '65518');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('marilyn', 'watkins', 'marilyn.watkins@example.com', '6265 hamilton ave', 'bueblo', 'georgia', '23299');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('kelly', 'lawson', 'kelly.lawson@example.com', '2986 station road', 'portarlington', 'louth', '84755');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('lilja', 'murto', 'lilja.murto@example.com', '7611 nordenskiöldinkatu', 'kitee', 'northern ostrobothnia', '50607');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('mackenzie', 'wang', 'mackenzie.wang@example.com', '9197 panama road', 'upper hutt', 'southland', '68617');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('lesa', 'horton', 'lesa.horton@example.com', '6967 nowlin rd', 'belen', 'kansas', '23873');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('hilla', 'hanka', 'hilla.hanka@example.com', '6285 myllypuronkatu', 'kangasala', 'tavastia proper', '96710');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('vincent', 'jackson', 'vincent.jackson@example.com', '7232 tamaki drive', 'whanganui', 'marlborough', '55395');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('ondina', 'de souza', 'ondina.desouza@example.com', '4357 rua santa maria ', 'suzano', 'minas gerais', '41840');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('?????', '?????? ????', '?????.??????????@example.com', '7730 ?????? / ????', '?????', '?????', '22691');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('curtis', 'wade', 'curtis.wade@example.com', '8392 new road', 'loughrea', 'cork city', '53237');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('lotta', 'waara', 'lotta.waara@example.com', '8732 rautatienkatu', 'leppävirta', 'finland proper', '83929');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('freddy', 'obispo', 'freddy.obispo@example.com', '4944 vleutenseweg', 'huizen', 'limburg', '54957');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('tale', 'alsaker', 'tale.alsaker@example.com', 'munkerudåsen 3870', 'sandeid', 'nord-trøndelag', '4307');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('jara', 'lacroix', 'jara.lacroix@example.com', '2235 rue de cuire', 'genthod', 'basel-stadt', '4739');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('xavier', 'caldeira', 'xavier.caldeira@example.com', '2098 rua primeiro de maio ', 'vila velha', 'distrito federal', '28119');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('solano', 'da conceição', 'solano.daconceição@example.com', '9492 rua principal', 'vila velha', 'são paulo', '34433');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('ozan', 'diemel', 'ozan.diemel@example.com', '8534 prins hendriklaan', 'stichtse vecht', 'drenthe', '24848');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('gina', 'clark', 'gina.clark@example.com', '5197 thornridge cir', 'albany', 'queensland', '8336');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('eli', 'banks', 'eli.banks@example.com', '1106 ranchview dr', 'bunbury', 'new south wales', '8422');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('jonathan', 'poulsen', 'jonathan.poulsen@example.com', '4387 fjordvej', 'ishoej', 'hovedstaden', '59516');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('belarmino', 'freitas', 'belarmino.freitas@example.com', '7261 rua sete de setembro ', 'maracanaú', 'amapá', '71037');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('ethan', 'singh', 'ethan.singh@example.com', '1009 frederick ave', 'inwood', 'northwest territories', 'G0O 9P7');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('filippa', 'sture', 'filippa.sture@example.com', 'hockeyveien 7228', 'straume', 'rogaland', '4150');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('jonah', 'bu', 'jonah.bu@example.com', 'hanåveien 183', 'monssveen', 'møre og romsdal', '6201');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('wallace', 'peterson', 'wallace.peterson@example.com', '5529 w dallas st', 'tamworth', 'new south wales', '7234');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('thea', 'morris', 'thea.morris@example.com', '8844 lake terrace', 'hamilton', 'canterbury', '53300');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('isaiah', 'terry', 'isaiah.terry@example.com', '5308 westmoreland street', 'nenagh', 'sligo', '21183');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('olivia', 'madsen', 'olivia.madsen@example.com', '1379 dyssevænget', 'juelsminde', 'nordjylland', '40293');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('shannon', 'diaz', 'shannon.diaz@example.com', '4449 hogan st', 'traralgon', 'western australia', '1287');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('vidar', 'joling', 'vidar.joling@example.com', '3083 mariaplaats', 'oisterwijk', 'friesland', '27458');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('cooper', 'king', 'cooper.king@example.com', '6208 dickens street', 'hamilton', 'northland', '94964');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('hans dieter', 'stork', 'hans dieter.stork@example.com', 'berliner straße 148', 'penkun', 'brandenburg', '25128');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('sergio', 'byrd', 'sergio.byrd@example.com', '2374 cork street', 'mallow', 'laois', '67825');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('german', 'hidalgo', 'german.hidalgo@example.com', '3228 calle del barquillo', 'vigo', 'navarra', '89718');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('william', 'jørgensen', 'william.jørgensen@example.com', '2963 dalsvinget', 'odense sv', 'danmark', '50184');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('???', '????? ???', '???.????????@example.com', '2944 ????? ?????', '??????', '?????', '94662');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('sílnior', 'da costa', 'sílnior.dacosta@example.com', '5533 rua das flores ', 'gravataí', 'sergipe', '87610');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('leonard', 'rey', 'leonard.rey@example.com', '9400 rue de labbé-grégoire', 'coeuve', 'uri', '6438');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('filippa', 'petersen', 'filippa.petersen@example.com', '3327 kildegårdsvej', 'nørre sundby', 'nordjylland', '34107');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('edwin', 'jacobs', 'edwin.jacobs@example.com', '4511 camden ave', 'rockhampton', 'queensland', '8082');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('lourens', 'passchier', 'lourens.passchier@example.com', '2815 wed', 'bergen', 'noord-brabant', '11815');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('olivia', 'thomas', 'olivia.thomas@example.com', '9742 anzac drive', 'whangarei', 'taranaki', '45512');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('gary', 'andrews', 'gary.andrews@example.com', '2089 west street', 'liverpool', 'fife', 'G2L 8PH');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('tyler', 'lewis', 'tyler.lewis@example.com', '9738 maraekakaho road', 'blenheim', 'canterbury', '65589');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('jael', 'boontjes', 'jael.boontjes@example.com', '2716 plompetorengracht', 'hollands kroon', 'zeeland', '13313');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('léandro', 'morin', 'léandro.morin@example.com', '4771 rue pasteur', 'rueil-malmaison', 'meurthe-et-moselle', '75649');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('lydia', 'pierre', 'lydia.pierre@example.com', '8937 rue de gerland', 'chur', 'appenzell innerrhoden', '4629');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('mario', 'lucas', 'mario.lucas@example.com', '9989 oaks cross', 'swansea', 'avon', 'PZ8Y 4QR');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('nelli', 'neva', 'nelli.neva@example.com', '1380 esplanadi', 'merijärvi', 'finland proper', '24090');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('jeppe', 'larsen', 'jeppe.larsen@example.com', '3489 lundevej', 'ansager', 'midtjylland', '35630');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('jenny', 'campbell', 'jenny.campbell@example.com', '9709 park avenue', 'cashel', 'clare', '34811');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('malak', 'habberstad', 'malak.habberstad@example.com', 'skullerudstubben 6679', 'kjellmyra', 'rogaland', '6727');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('çetin', 'sadiklar', 'çetin.sadiklar@example.com', '1385 necatibey cd', 'batman', 'bursa', '12099');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('hilla', 'perko', 'hilla.perko@example.com', '6789 pyynikintie', 'virrat', 'kainuu', '44544');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('ethel', 'garza', 'ethel.garza@example.com', '519 hickory creek dr', 'pueblo', 'california', '21848');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('zoe', 'margaret', 'zoe.margaret@example.com', '2342 park rd', 'hampstead', 'ontario', 'B3Z 8O8');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('jacob', 'olsen', 'jacob.olsen@example.com', '2657 lyøvej', 'askeby', 'sjælland', '44777');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('giovani', 'fogaça', 'giovani.fogaça@example.com', '9726 rua da paz ', 'gravataí', 'rio grande do norte', '57215');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('juho', 'halonen', 'juho.halonen@example.com', '2395 siilitie', 'virolahti', 'south karelia', '24329');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('célestin', 'dubois', 'célestin.dubois@example.com', '2153 place de labbé-basset', 'saint-pierre', 'pyrénées-atlantiques', '10569');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('manuela', 'nuñez', 'manuela.nuñez@example.com', '7116 calle del pez', 'alcobendas', 'andalucía', '83084');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('oliver', 'kantola', 'oliver.kantola@example.com', '1726 siilitie', 'luvia', 'päijät-häme', '32974');
INSERT INTO  (first_name, last_name, email, street, city, state, postcode) VALUES ('????', '????? ???', '????.????????@example.com', '6070 ??????', '??????', '?????', '56553');




