places = ['Egipto','Londres','Japon','Brasil','China']
print('Lista original')
print(places)
print('Lista ordenada alfabeticamente')
print(sorted(places))
print('Lista original')
print(places)
print('Lista ordenada y al reverso')
places.sort(reverse=True)
print(places)
print('Lista al reverso = a la original')
places.reverse()
print(places)
print('Lista ordenada permanentemente')
places.sort()
print(places)
print('Lista al reves permanente')
places.sort(reverse=True)
print(places)

