version: "3.5"
services:
  app:
    build: ./app
    container_name: dc_app
    networks:
      - dc
    depends_on:
      - "postgres"
    restart: on-failure:10
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app

  script:
    build: ./app
    container_name: dc_script
    networks:
      - dc
    depends_on:
      - "postgres"
    restart: on-failure:10
    volumes:
      - ./app:/usr/src/app
    command: ["python", "./populate.py"]

  postgres:
    container_name: dc_db
    image: postgres
    environment:
      POSTGRES_DB: dc_heroes
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      #PGDATA: /data/postgres
    volumes:
       - $PWD/pg-data/:/data/postgres
       - ./db:/docker-entrypoint-initdb.d/:ro
    ports:
      - "5432:5432"
    networks:
      - dc
    restart: unless-stopped
  
  pgadmin:
    container_name: dc_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - $PWD/pgadmin-data/:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - dc
    depends_on:
      - "postgres"
    restart: unless-stopped
  
  redis:
    image: redis:latest
    container_name: dc_redis
    ports:
      - 6379:6379
    volumes:
      - type: bind
        source: ./config/redis.conf
        target: /redis.conf
    command: ["redis-server", "/redis.conf"]
    networks:
      - dc

networks:
  dc:
    driver: bridge