version: "3.7"
services:
    mongodb:
        container_name: mongo_db
        image: mongo:4.4
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: Admn
            MONGO_INITDB_ROOT_PASSWORD: fish4life
            MONGO_INITDB_DATABASE: fishes

        volumes:
          - volumeMongo:/var/lib/docker/volumes/mongoVolume/_data

    mongo-express:
        container_name: dbms
        image: mongo-express
        restart: always
        ports:
            - "8082:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: Admn
            ME_CONFIG_MONGODB_ADMINPASSWORD: fish4life
            ME_CONFIG_BASICAUTH_USERNAME: Admn
            ME_CONFIG_BASICAUTH_PASSWORD: fish4life
            
volumes:
    volumeMongo: