FROM python:3.8


WORKDIR /home/GeorgeHdz/Documentos/Dis_Arq_Software/DAS_Sistemas/Ene-Jun-2021/hernandez-vazquez-jorge-de-jesus/Practicas/2doParcial/Practica2/parte3/dockers/


COPY . /home/GeorgeHdz/Documentos/Dis_Arq_Software/DAS_Sistemas/Ene-Jun-2021/hernandez-vazquez-jorge-de-jesus/Practicas/2doParcial/Practica2/parte3/dockers/


RUN pip install --no-cache-dir -r requeriments.txt

# run the command
CMD ["python", "./scrpt.py"]