version: "3.8"
services:
  postgresql:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: dm16
      PGDATA: /var/lib/postgresql/data
    ports:
    - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: salazar_daniel@hotmail.es
      PGADMIN_DEFAULT_PASSWORD: dm16
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "8080:80"
    links: postgresql

  python:
    container_name: insertador
    image: python:3
    run: pip3 install -r requirements.txt
    command: python3 orm.py