version: "3.8"
services:
  # We create 3 workers
  worker_1:
    build: .
    restart: on-failure:10
    container_name: goworker_1
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    depends_on:
      - rabbitmq
    command: go run ./worker/main.go
  worker_2:
    build: .
    restart: on-failure:10
    container_name: goworker_2
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    depends_on:
      - rabbitmq
    command: go run ./worker/main.go
  worker_3:
    build: .
    restart: on-failure:10
    container_name: goworker_3
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    depends_on:
      - rabbitmq
    command: go run ./worker/main.go
  # Task queue restarts always for sending new messages
  queue:
    build: .
    restart: always
    container_name: gotask_queue
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    depends_on:
      - rabbitmq
    command: go run ./new_task/main.go Message.....
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: my-rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=therabbit
      - RABBITMQ_DEFAULT_PASS=secret123
  